Name: Destiny MARTINEZ

Lab partner(s): 

In [ ]:
Paola Granados

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner in your breakout room, they are your partner for this lab. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Blackboard.

# Warmups

**W.1** Define a string variable that has the value "All my exes live in Texas". Print out the word Texas from this string two ways, using both postive and negative indexing.

In [4]:
tex = ['all', 'my', 'exes', 'live', 'in', 'Texas']

x= 'all my exes live in Texas'

In [5]:
tex[5]

'Texas'

In [6]:
tex[-1]

'Texas'

**W.2** How many times is the letter e used in the above?

In [8]:
count_e_x = x.count('e')

count_e_x

4

**W.3** Define both a list and a numpy array that has even integers from 0 to 20

In [9]:
import numpy as np 

In [10]:
list_ = [0,2,4,6,8,10,12,14,16,18,20]

np_array= np.array(list_)

np_arrange= np.arange(0,12,2)

In [11]:
np_arrange

array([ 0,  2,  4,  6,  8, 10])

**W.4** Add this array to itself, what is the result? Do the same thing with a list, how is the result different?

In [12]:
list_+ list_

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [13]:
np_array+ np_array

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

**W.5** Find the mean of the numpy array you created using a method and a function.

In [19]:
average_methods= np.mean(np_array)

In [20]:
average_functions

NameError: name 'average_functions' is not defined

In [21]:
average_methods

10.0

**W.6** Now try finding the mean of the list, does it work in the same way?

In [23]:
average_list= sum(list_)/len(list_)

In [24]:
average_list

10.0

# Lecture 3.1

Lecture Agenda:

* questions so far
* standard import statements
* basic things in numpy and matplotlib
* how to investigate how a pre-defined function works
* First plot! 

In general, your python notebook, interactive session, or script will start with some importing statements to add the packages you are going to use. Below we will go over the most standard ones and make a simple plot

In [ ]:
import numpy as np                        # load the numerical python package
import matplotlib.pyplot as plt           # load the plotting package

Note you only have to load the packages once, then they are available in your kernel. If you restart the kernel, you need to reload the packages. You can check what packages are loaded using whos, just like for variables

In [ ]:
whos

Let's make a basic plot, a sine wave. Fist we have to define the x-axis data, the points we want to plot. You can type these all out, but numpy has a few functions to create this date, let's use one.

Look at the documentation for the numpy function *arange*. The inputs are start, stop and step, and there are some examples at the bottom. Some of these inputs are optional. Let's play around with this

In [ ]:
np.arange?

If we type the arange function without assigning it to a variable, the result will be printed out instead of stored in a variable. Let's use this to explore how this function works.

In [ ]:
np.arange(5) # the 5 here is the "stop"

The result is that the array starts at zero and stops before 5, similar to how indexing works. We can get the same result by specifying a starting number

In [ ]:
np.arange(0,5) # here 0 is the "start", this gives you the same result

What about if we add three arguments to the function? Let's try

In [ ]:
np.arange(1,100,2) # here the 2 is the "stride"

Let's define an x basis array that goes from -2$\pi$ to 2$\pi$ in steps of $\pi$/8. First we will check it out, then do the assignment. We will use np.pi for $\pi$. I'm going to define the start, stop and step values as variables to make the function syntax clearer.

In [ ]:
np.pi

In [ ]:
start = -2*np.pi
stop = 2*np.pi
step = np.pi/8

np.arange(start, stop, step) # this is wrong, why?

The numpy array doesn't go to 2$\pi$, but stops before this. This is because it doesn't go all the way to the stop value, but ends at stop - step. How can we fix this?

In [ ]:
# note my start, stop and step are defined above, so I can reuse them here.

np.arange(start, stop+step, step) # now it works

NOW the array ends at 2$\pi$. Let's save this to an array we can use later.

In [ ]:
x = np.arange(start, stop+step, step)
# check:
x

Next we need to define the y-values for our plot, using the np.sin function. We will use the x array we just created.

In [ ]:
# note the input has to be in radians, not degrees
np.sin?

In [ ]:
y = np.sin(x)
y #check

The most basic plotting command:

In [ ]:
plt.plot(x,y)

# note this uses the shortcut we created when we used the import statement: 
# import matplotlib.pyplot as plt 
# otherwise you would have to type matplotlib.pyplot.plot(x,y)

You can see above that the plot is kind of choppy. To fix this we need to have more x points and fill in the plot more

In [ ]:
start = -2*np.pi
stop = 2*np.pi
#step = np.pi/8
step = np.pi/16

x_2 = np.arange(start,stop,step)

In [ ]:
# note we can just put the np.sin function call right inside the plotting statement

plt.plot(x_2, np.sin(x_2))


Looks much better with more x values

In [ ]:
# add some labels and a title in

plt.plot(x_2, np.sin(x_2))
plt.xlabel('x')
plt.ylabel('y')
plt.title('y = sin(x)')

We can save the plot by using python functions, or just right click and copy or saveas...

In [ ]:
plt.savefig?

In [ ]:
# add some labels and a title in

plt.plot(x_2, np.sin(x_2))
plt.xlabel('x')
plt.ylabel('y')
plt.title('y = sin(x)')

plt.savefig('sin.png')
plt.savefig('sin_HR.png', dpi = 900) # higher resolution, dpi = "dots per square inch"

# Lab 3.1

**E.1** Complete Complete Ch 4 of Introduction to Python in datacamp: Numpy

**E.2** What are the differences between lists and arrays? Demonstrate.

In [25]:
import numpy as np

In [ ]:
#lists contain different types of data and arrays can only contain one type such as math.

**E.3** Using the numpy function arange, make an array of even intergers that goes from 0 to 20, and includes 20.

In [26]:
my_array= np.arange(0,22,2)

**E.4** Using the above and logical (boolean) indexing, make an array that has even integers from 10 to 20, including 10 and 20.

In [27]:
new= my_array[my_array%2 ==0]
new[5:]

array([10, 12, 14, 16, 18, 20])

**E.5** What is the shape of the array you just created?

In [28]:
new.shape

(11,)

**E.6** Plot the function $y=(x+4)(x-3)(x+1)^2$ over the interval [-5, 5]. Make sure you include the endpoints of this interval and use enough points so that your plot looks smooth. Label your axes and add a title that includes the function you just plotted. Save this plot to both a .png and .pdf file using python commands, and copy and paste the plot directly from this notebook into a word document. 

In [48]:
start=-5
stop=5
step=0.001

In [49]:
x= np.arange(start, stop+step, step)

In [50]:
x

array([-5.   , -4.999, -4.998, ...,  4.999,  5.   ,  5.001])

In [51]:
y= (x+4)*(x-3)*(x+1)**2

In [54]:
plt.plot (x,y)

plt.xlabel('x')
plt.ylabel('y')
plt.title('$y=(x+4)(x-3)(x+1)^2$')

NameError: name 'plt' is not defined

**E.7** Find the approximate minimum value of the function in **E.6**. How does your definition of the x-value basis array affect this minimum? Demonstrate.

In [55]:
start = -5
stop = 5
step = 0.1

In [56]:
x = np.arange(start, stop+step, step)
y = (x+4)*(x-3)*(x+1)**2

y=min(y)
print(y)

-54.580900000000064


**E.8** Using logical (boolean) indexing, plot the function again but only the negative values.

In [57]:
start = -5
stop = 0
step = 0.1

x = np.arange(start, stop+step, step)
y = (x+4)*(x-3)*(x+1)**2

plt.plot(x,y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('$y=(x+4)(x-3)(x+1)^2$')

NameError: name 'plt' is not defined

**E.9** Given the numpy array below, find two ways to add 10 to the first column and 20 to the second column. Hint: you can do this in one line.

In [59]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

In [61]:
x = np_mat+ ([10,20],
            [0,0],
            [0,0])
print(x)

[[11 22]
 [ 3  4]
 [ 5  6]]


**E.10** Add 10 to the second row of the above array

In [62]:
y = np_mat + ([0,0],
             [10,10],
             [0,0])
print(y)

[[ 1  2]
 [13 14]
 [ 5  6]]


**E.11** Define an array that has eight columns and ten rows and is full of ones

In [63]:
array= np.ones((8,10))
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**E.12** Turn all of the ones in the interior of your array to fives, that is everything but the first and last rows and first and last columns.

In [64]:
update = array + ([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])
print(update)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 1. 1. 1. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 1. 1. 1. 5.]
 [5. 1. 1. 1. 1. 1. 1. 1. 1. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


**E.13** Using logical indexing, turn all of the fives to eights

In [65]:
np_update = np.array(update)
np_update2 = np.where(np_update > 4, 8, np_update)
print(np_update2)

[[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 1. 1. 1. 1. 1. 1. 1. 1. 8.]
 [8. 1. 1. 1. 1. 1. 1. 1. 1. 8.]
 [8. 1. 1. 1. 1. 1. 1. 1. 1. 8.]
 [8. 1. 1. 1. 1. 1. 1. 1. 1. 8.]
 [8. 1. 1. 1. 1. 1. 1. 1. 1. 8.]
 [8. 1. 1. 1. 1. 1. 1. 1. 1. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]


**E.14** Plot the resulting 2D array and add a colorbar (google it!).

In [66]:
x = np_update2
c = plt.imshow(x)
plt.colorbar(c, shrink = 1.25)
plt.plot()

NameError: name 'plt' is not defined