Name destiny martinez

Labpartner(s)

In [1]:
#import statements go here
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Lab 4.2 

Wednesday labs are due Sunday at midnight

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner in your breakout room, they are your partner for this lab. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Blackboard.

# Warmups 4.2

W.1-3 Do exercises 1-3 in http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 4.1  on how to load in the data file

In [2]:
data = np.loadtxt('populations.txt')
year, hares, lynxes, carrots = data.T
populations = data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [3]:
#largest population for chart above ; type idx.max
print("hares, lynxes, carrots")
print("mean", populations.mean(axis=0))
print("Std:", populations.std(axis=0))

hares, lynxes, carrots
mean [34080.95238095 20166.66666667 42400.        ]
Std: [20897.90645809 16254.59153691  3322.50622558]


In [9]:
# mean and standard deviation
hare_mean = np.mean(data[:,1])
hare_mean

34080.95238095238

In [10]:
carrot_mean = np.mean(data[:,3])
carrot_mean

42400.0

In [11]:
np.max(hares)

77400.0

In [12]:
np.where(hares == 77400)

(array([3], dtype=int64),)

In [15]:
np.max(lynxes)

59400.0

In [16]:
np.where(lynxes == 59400)

(array([4], dtype=int64),)

In [18]:
np.max(carrots)

48300.0

In [19]:
np.where(carrots == 48300)

(array([0], dtype=int64),)

In [20]:
years = data[:,0]
years

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [21]:
data1 = data[:,1:4]
data1

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [22]:
np.argsort(data1)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [0, 2, 1],
       [0, 2, 1],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]], dtype=int64)

In [23]:
max_species = np.argmax(data1, axis = 1)

In [24]:
species = np.array(['hares','lynxes','carrot'])
max_species1 = species[max_species]
maxpopulation = np.column_stack((years, max_species1))
maxpopulation

array([['1900.0', 'carrot'],
       ['1901.0', 'carrot'],
       ['1902.0', 'hares'],
       ['1903.0', 'hares'],
       ['1904.0', 'lynxes'],
       ['1905.0', 'lynxes'],
       ['1906.0', 'carrot'],
       ['1907.0', 'carrot'],
       ['1908.0', 'carrot'],
       ['1909.0', 'carrot'],
       ['1910.0', 'carrot'],
       ['1911.0', 'carrot'],
       ['1912.0', 'hares'],
       ['1913.0', 'hares'],
       ['1914.0', 'hares'],
       ['1915.0', 'lynxes'],
       ['1916.0', 'carrot'],
       ['1917.0', 'carrot'],
       ['1918.0', 'carrot'],
       ['1919.0', 'carrot'],
       ['1920.0', 'carrot']], dtype='<U32')

# Lecture 4.2

Agenda:
- Coding questions
- Tabs in python. 

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE
- All about final projects

See final project files on github under Course Materials folder

# Lab 4.2

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/IntroSciComp_S2021/blob/main/Class_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

**E.3** Exercise 1 on https://www.practicepython.org

In [1]:
name = input("please enter your name here: ")
age = int(input("enter your age here: "))
b = str((100 - age) + 2021)
print(name+ " will be 100 years old in the year " + b)

please enter your name here: destiny
enter your age here: 22
destiny will be 100 years old in the year 2099


**E.4** Exercise 2 on https://www.practicepython.org

In [2]:
copy = input(name+", give me a random number:")

destiny, give me a random number:150


In [5]:
print((name+"will be 100 years old in the year"+ str(b)+"/n")*int(copy))

destinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in the year2099/ndestinywill be 100 years old in th

In [1]:
#exercise 2
num = input("Hi! input a random number:")

Hi! input a random number:5


In [2]:
if int(num)%2 == 0:
    print("your number is even")
else:
    print("your number is odd")

your number is odd


In [3]:
check = input("give me a random number to add"+num+":")

give me a random number to add5:6


In [4]:
if int(num)%int(check)== 0:
    print(num+"add by"+check)
else:
    print(num+ "add odd"+check)

5add odd6


Don't forget to do some practicing of what you have been learning, including previous labs

**You did it!**