Name Destiny Martinez

Labpartner(s): Paula Granados

In [25]:
# import statements go here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [26]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [27]:
a.ndim

1

In [28]:
a.shape

(4,)

In [29]:
len(a)

4

In [30]:
#2-D
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
b.ndim

2

In [32]:
b.shape

(2, 3)

In [33]:
#3D
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [34]:
c.shape

(2, 2, 1)

In [35]:
#two dimensional
array1 = np.array([[1,3,5,7,9], [0,2,4,6,8]])
array1

array([[1, 3, 5, 7, 9],
       [0, 2, 4, 6, 8]])

In [36]:
#creating functions
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b = np.arange(1,9,3)
b

array([1, 4, 7])

In [40]:
c = np.linspace(0,1,6)
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [49]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

In [50]:
a= np.ones((3,3)) #common array
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [53]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
d = np.diag(np.array([1,2,3,4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [55]:
a = np.random.rand(4)
a

array([0.45420219, 0.27720403, 0.35069938, 0.06244729])

In [56]:
b = np.random.randn(4)
b

array([1.37759025, 0.8535025 , 0.23259698, 1.38495809])

In [57]:
np.random.seed(1234)

In [58]:
#creating a 4x3 array
np.random.rand(4,3)

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261],
       [0.27646426, 0.80187218, 0.95813935],
       [0.87593263, 0.35781727, 0.50099513]])

In [59]:
np.random.seed(1998)
array2 = np.random.rand(4,3)
array2

array([[0.55944558, 0.76149199, 0.24453155],
       [0.77168947, 0.35447208, 0.7966974 ],
       [0.34600002, 0.44387444, 0.30330359],
       [0.44211392, 0.57320936, 0.06566402]])

In [60]:
array3= np.empty([3,3])
array3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Lecture 5.2

### Agenda:

- Programming questions
- Dr. Coupe will show some plots 
- Examples of for loops

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [61]:
import numpy as np
np.random.rand(123) #random seed random numbers

array([0.02408889, 0.82062263, 0.36513765, 0.72209402, 0.40108054,
       0.55502968, 0.2236308 , 0.81431877, 0.75928433, 0.79281004,
       0.68130607, 0.55321588, 0.768093  , 0.96183113, 0.95405944,
       0.54846018, 0.25344207, 0.22208241, 0.68772864, 0.69237079,
       0.09547832, 0.74964779, 0.01163001, 0.15849499, 0.29236258,
       0.8058657 , 0.78930835, 0.98889497, 0.0257536 , 0.7461169 ,
       0.56427586, 0.68161481, 0.19128774, 0.89627949, 0.81459533,
       0.17511027, 0.86832801, 0.4726625 , 0.03288983, 0.36906691,
       0.77625449, 0.01891093, 0.62604042, 0.36272232, 0.36671872,
       0.81242554, 0.44837065, 0.70090955, 0.37877523, 0.34188245,
       0.12799851, 0.60638254, 0.86414718, 0.14975816, 0.08217687,
       0.6444111 , 0.02370595, 0.72980417, 0.99542517, 0.43300357,
       0.40782723, 0.77321379, 0.16803656, 0.19650295, 0.99463854,
       0.91762879, 0.8392536 , 0.55679065, 0.54161695, 0.47673755,
       0.74602124, 0.02360639, 0.80788612, 0.75427542, 0.55635

In [63]:
coin = np.random.randint(0,2)
print(coin)
if coin == 0:
    print("heads")
else: 
    print("tails")

1
tails


### Congratulations! ¡Felicidades! You finished Intermediate Python!