Name: Paola Granados

Lab partner: Adam Sanjar

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner in your breakout room, they are your partner for this lab. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Blackboard.

# Lecture 2.1

Lecture Agenda:
* more review of indexing (before warmups)
* go over syllabus, grading
* introduction of assessment exercise
* questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [1]:
title = "Monty Python"

In [2]:
# How do I print out "Monty" and "Python"?

#Monthy
print(title[0:5])

#Python
print(title[6:12])

Monty
Python


In [3]:
# You don't have to specify the beginning or the end index

#Monty
print(title[:5])

#Python
print(title[6:])

Monty
Python


In [4]:
# How do I print them out using negative indices?

#Python
print(title[-6:])

#Monty
print(title[-12:-7])

Python
Monty


# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [5]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [6]:
#first element
print(list1[0])

1


In [7]:
#last element
print(list1[-1])

10


**W.3** Print the second element through the ninth element of list1

In [8]:
print(list1[1:9])

[2, 3, 4, 5, 6, 7, 8, 9]


**W.4** Print the sum of the first and last elements of list1

In [9]:
print(list1[0]+list1[-1])

11


**W.5** Print the product of the second and third element of list1

In [10]:
print(list1[1]*list1[2])

6


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [11]:
list2 = [list1[1],list1[3],list1[5],list1[7],list1[9]]
print(list2)

[2, 4, 6, 8, 10]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [12]:
print(list1[4]+list2[4])

15


**W.8** Print the product of the second element of list1 and the second element of list2.

In [13]:
print(list1[1]*list2[1])

8


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [14]:
list1[0]=5
print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [15]:
list2[-1]=5
print(list2)

[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [16]:
list3 = list1+list2
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [17]:
list4 = list3 + ["Paola","Granados"]
print(list4)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Paola', 'Granados']


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [18]:
who

list1	 list2	 list3	 list4	 title	 


In [19]:
whos

Variable   Type    Data/Info
----------------------------
list1      list    n=10
list2      list    n=5
list3      list    n=15
list4      list    n=17
title      str     Monty Python


In [20]:
print(list1)
print(list2)
print(list3)
print(list4)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 5]
[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]
[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Paola', 'Granados']


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

    An error ocurred, which didn't allow the lists to be printed again. This happened because when you restart the notebook, you kind of clear the memory of the notebook. This means that when you restart the notebook, there are no variables saved, and you would have to rerun each kernel to store the variables.

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

    A function is a set of code that already has a predisposed task for it to do. For example, type() is a function that will return the type a variable is, once the variable is inputted. Another example is round() as it is set to round the inputted number. 

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

    To get help with a function, you can ask python for help. Running help() with whatever element you want more information inputted will return information on the function

In [21]:
#Example - Getting help for round()
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



**E.4** What is a method? How is it different from a function? Demonstrate

    A method is a function that belongs to a specific object. It is different from a function in that a method is specific to a variable type, and method for one variable type, for example list, may not be found in a method for a different type of variable, for example a string. 

In [22]:
#using method .append for a list
list = [3, 4, 5, 6]
list.append(7)
print(list)

[3, 4, 5, 6, 7]


In [23]:
#trying the same method .append for a string
string = "string"
string.append(7)
#error message states that str object has no attribute append

AttributeError: 'str' object has no attribute 'append'

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [24]:
#Using a function to determine max of list1
max(list1)

10

In [25]:
#using a method
# sort method is used to sort list values from least to greatest
list1.sort()
print(list1)
#10 is the greatest one, therefore the maximum value

[2, 3, 4, 5, 5, 6, 7, 8, 9, 10]


**E.6** Repeat W.12 using a method

In [26]:
list3.append("Paola")
list3.append("Granados")
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Paola', 'Granados']


**E.7** What is a python package?

    A python package is a directory of python scripts. Each python script has a set of modules, which specify new functions, methods, and types you can use. 

In the anaconda .distribution you all have, most of the packages you will need are already installed. Later on, we will go over how to add more packages

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

    To instus an installed package, you have to call it out in your code every time you want to use it. You will use import ________ with the name of the package to call it out. 

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [27]:
import numpy as np 
array1 = np.array([1,2,3,4,5,6,7,8,9,10])
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**E.10** Repeat W.2-W.6 using arrays

In [28]:
#W.2 Print the first element of array1, then print the last element of array1
array1[0]

1

In [29]:
array1[-1]

10

In [30]:
#W.3  Print the second element through the ninth element
array1[1:9]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#W.4 Print the sum of the first and last elements
array1[0]+array1[-1]

11

In [32]:
#W.5 Print the product of the second and third element
array1[1]*array1[2]

6

In [33]:
#W.6 Create a new array of only the even numbers of array1 Name the new array array2
array2 = np.array([array1[1],array1[3],array1[5],array1[7],array1[9]])
array2

array([ 2,  4,  6,  8, 10])

### Practice 

In [34]:
listp = [4,2,9,1,5,1,8]

Practice using functions 

In [35]:
# max function selects the max value
max(listp)

9

In [36]:
#min function
min(listp)

1

In [37]:
# len function gives the length of an object
len(listp)

7

In [38]:
#locals returns the current local symbol table 
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'title = "Monty Python"',
  '# How do I print out "Monty" and "Python"?\n\n#Monthy\nprint(title[0:5])\n\n#Python\nprint(title[6:12])',
  "# You don't have to specify the beginning or the end index\n\n#Monty\nprint(title[:5])\n\n#Python\nprint(title[6:])",
  '# How do I print them out using negative indices?\n\n#Python\nprint(title[-6:])\n\n#Monty\nprint(title[-12:-7])',
  'list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
  '#first element\nprint(list1[0])',
  '#last element\nprint(list1[-1])',
  'print(list1[1:9])',
  'print(list1[0]+list1[-1])',
  'print(list1[1]*list1[2])',
  'list2 = [list1[1],list1[3],list1[5],list1[7],list1[9]]\nprint(list2)',
  'print(list1[4]+list2[4])',
  'print(list1[1]*list2[1])',
  'list1[0]

In [39]:
#sorted function
sorted(listp)

[1, 1, 2, 4, 5, 8, 9]

Methods of a list 

In [40]:
help(list)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [41]:
#sort method - reverse = True makes it from greatest to least
listp.sort(reverse=True)
listp

[9, 8, 5, 4, 2, 1, 1]

In [42]:
#sort method - reverse = False arranges it from least to greatest
listp.sort(reverse=False)
listp

[1, 1, 2, 4, 5, 8, 9]

In [45]:
#append method - adds an item to the list
listp.append(9)
listp
listp.append([9,5,6])
listp

[1, 1, 2, 4, 5, 8, 9, 9, 9, [9, 5, 6]]

In [46]:
#remove method - remove the first item whose value is equal to x
listp.remove([9,5,6])
listp

[1, 1, 2, 4, 5, 8, 9, 9, 9]

In [47]:
#count method - return the number of times x appears
listp.count(1)

2

Numpy Arrays 

In [48]:
#numpy was imported earlier

In [49]:
#1D array - making list p into an array 
arrayp = np.array(listp)
arrayp

array([1, 1, 2, 4, 5, 8, 9, 9, 9])

In [50]:
#multiplying arrayp vs multiplying listp

In [51]:
arrayp*2

array([ 2,  2,  4,  8, 10, 16, 18, 18, 18])

In [52]:
listp*2

[1, 1, 2, 4, 5, 8, 9, 9, 9, 1, 1, 2, 4, 5, 8, 9, 9, 9]