Name: Paola Granados

Labpartner(s): Destiny Martinez

In [29]:
#import statements go here
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd 

# Lab 4.2 

Wednesday labs are due Sunday at midnight

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner in your breakout room, they are your partner for this lab. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Blackboard.

# Warmups 4.2

W.1-3 Do exercises 1-3 in http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 4.1  on how to load in the data file

In [12]:
#importing the data file 
data_np = np.loadtxt('http://scipy-lectures.org/_downloads/populations.txt')

In [13]:
data_np

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [25]:
#subset an array for each of the columns
hare = data_np[:,1]
lynx = data_np[:,2]
carrots = data_np[:,3]
years = data_np[:,0]

1. The mean and std of the populations of each species for the years in the period

In [21]:
#mean and standard deviation of hare
hare_mean = np.mean(hare)
hare_std = np.std(hare)
print(hare_mean)
print(hare_std)

34080.95238095238
20897.906458089667


In [22]:
#mean and standard deviation of lynx
lynx_mean = np.mean(lynx)
lynx_std = np.std(lynx)
print(lynx_mean)
print(lynx_std)

20166.666666666668
16254.591536908763


In [23]:
#mean and standard deviation of carrot
carrot_mean = np.mean(carrots)
carrot_std = np.std(carrots)
print(carrot_mean)
print(carrot_std)

42400.0
3322.5062255844787


2. Which year each species had the largest population.

In [31]:
#hare 
np.max(hare)

77400.0

In [34]:
#determine the index value for where max hare population is 
np.where(hare == 77400)

(array([3], dtype=int64),)

In [36]:
#YEAR OF MAXIMUM HARE POPULATION
years[3]

1903.0

In [37]:
#lynx
np.max(lynx)

59400.0

In [38]:
np.where(lynx == 59400)

(array([4], dtype=int64),)

In [39]:
#year of Maximum LYNX population 
years[4]

1904.0

In [40]:
#Carrots
np.max(carrots)

48300.0

In [42]:
np.where(carrots == 48300)

(array([0], dtype=int64),)

In [44]:
#year of Maximum CARROT population
years[0]

1900.0

3. Which species has the largest population for each year. (Hint: argsort & fancy indexing of np.array(['H', 'L', 'C']))

In [51]:
#create pop_array which excludes years data 
pop_array = data_np[:,1:4]
pop_array

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [52]:
#use argsort, max values will be in the third column
#argsort lists from least to greatest,where the return array has index number from input array
np.argsort(pop_array)

array([[1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [0, 2, 1],
       [0, 2, 1],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]], dtype=int64)

In [57]:
#Solution Manual 
max_species = np.argmax(pop_array, axis = 1)

In [60]:
#make an array with the names of organisms in their respective index
#use species array to convert max_species index value to the organism it represents
species = np.array(['Hare', 'Lynx', 'Carrot'])
max_species1= species[max_species]

In [67]:
maxpop_years= np.column_stack((years,max_species1))

In [68]:
maxpop_years

array([['1900.0', 'Carrot'],
       ['1901.0', 'Carrot'],
       ['1902.0', 'Hare'],
       ['1903.0', 'Hare'],
       ['1904.0', 'Lynx'],
       ['1905.0', 'Lynx'],
       ['1906.0', 'Carrot'],
       ['1907.0', 'Carrot'],
       ['1908.0', 'Carrot'],
       ['1909.0', 'Carrot'],
       ['1910.0', 'Carrot'],
       ['1911.0', 'Carrot'],
       ['1912.0', 'Hare'],
       ['1913.0', 'Hare'],
       ['1914.0', 'Hare'],
       ['1915.0', 'Lynx'],
       ['1916.0', 'Carrot'],
       ['1917.0', 'Carrot'],
       ['1918.0', 'Carrot'],
       ['1919.0', 'Carrot'],
       ['1920.0', 'Carrot']], dtype='<U32')

# Lecture 4.2

Agenda:
- Coding questions
- Tabs in python. 

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE
- All about final projects

See final project files on github under Course Materials folder

# Lab 4.2

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/IntroSciComp_S2021/blob/main/Class_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

x == y ; x is equal to y 
x != y; x is not equal to y 
X > y ; x is greater than y 
X < y ; x is less than y 

In [37]:
#Comparing arrays 
array1 = np.array([10,15,25])

array1>13 #this returns True for the numbers that ARE greater than 13

array([False,  True,  True])

In [39]:
#comparing two arrays 
array2 = np.array([2,3,30])

array2>array1 #returns True for where array 2 is greater than array 1

array([False, False,  True])

for simple Python, you can use and, or, not 
for numpy python, you use np.logical_and(), np.logical_or(), np.logical_not()

In [42]:
print(array1>12 and array1>array2)
#won't work because theyre arrays 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [43]:
#have to use np.logical statements to compare arrays 
np.logical_and(array1>1, array1>array2)

array([ True,  True, False])

In [44]:
#if we choose single elements from an array we can use simple and, or ,not
array1[1]>12 and array1[1]>array2[1]

True

IF STATEMENTS

if condition :
    action to complete if condition is true 
elif condition:
    action to comple if elif condition is true 
else:
    action to complete if conditions are false

**E.3** Exercise 1 on https://www.practicepython.org

Create a program that asks the user to enter their name and their age. Print out a message addressed to them that tells them the year they will turn 100 years old. 

In [1]:
# Input user's Name
name = input("Give me your name: ")
print("Your name is "+name )

Give me your name: Paola
Your name is Paola


In [2]:
#Input user's age
age = input(name + (", what is your age?"))

Paola, what is your age?21


In [3]:
#calculate the year in which user will turn 100
year = ((2021-int(age)+100))

In [4]:
print(name+" you will turn 100 years old in the year "+ str(year))

Paola you will turn 100 years old in the year 2100


Add on to the previous program by asking the user for another number and printing out that many copies of the previous message; print out that many copies on seperate lines

In [8]:
#Ask the user for another number 
copy = input(name+", give me a random number:")

Paola, give me a random number:2


In [9]:
#print out copies of the last statement 
print((name+" you will turn 100 years old in the year "+ str(year)+"\n")*int(copy))

Paola you will turn 100 years old in the year 2100
Paola you will turn 100 years old in the year 2100



**E.4** Exercise 2 on https://www.practicepython.org

Ask the user for a number. Depending on whether the number is even or odd, print out an appropriate message to the user. 

In [18]:
#Have the user input a number 
num = input("Hi! Input a number:")

Hi! Input a number:7


In [19]:
# If there is a remainder of 0 when divided by 2, the number is even
# else the number is odd
if int(num)%2 == 0:
    print("Your number is even")
else:
    print("Your number is odd")

Your number is odd


 If the number is a multiple of 4 print out a different message

In [20]:
if int(num)%4 == 0:
    print("your number is a multiple of 4 and it is even")
elif int(num)%2 == 0:
        print("Your number is even")
else: 
    print("Your number is odd")

Your number is odd


Ask the user for two numbers: one number to check (call it num) and one number to divide by (check). If check divides evenly into num tell that to the user. If not print a different appropriate message 

In [24]:
#ask to input check 
check = input("give me a number to divide by "+ num + ": ")

give me a number to divide by 7: 2


In [25]:
if int(num)%int(check) == 0:
    print (num+" divides evenly by "+check)
else:
    print(num+ " does NOT divide evenly by "+check)

7 does NOT divide evenly by 2


Don't forget to do some practicing of what you have been learning, including previous labs

**You did it!**