Name: Paola Granados

Labpartner(s): Destiny Martinez

In [2]:
# import statements go here
import numpy as np 
import pandas as pd

# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

Manual Construction of Arrays 

In [15]:
#1-D Array :
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [5]:
#check dimension
a.ndim

1

In [6]:
#check shape
a.shape

(4,)

In [8]:
#check length 
len(a)

4

In [14]:
#2-D Array 
b = np.array([[0, 1, 2], [3, 4, 5]]) 
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
len(b)

2

In [13]:
#3-D Array
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [16]:
c.shape


(2, 2, 1)

Create a simple two dimensional array. First, redo the examples from above. And then create your own: how about odd numbers counting backwards on the first row, and even numbers on the second?

In [41]:
array1 = np.array([[9,7,6,5,4],[10,8,6,4,2]])
array1

array([[ 9,  7,  6,  5,  4],
       [10,  8,  6,  4,  2]])

Functions for creating arrays

In [17]:
a = np.arange(10) #creates an array with a range up to 10th index
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.arange(1,9,2)#array starts at 1, exclusive end at 9 (so 9 is not included), goes by 2 
b

array([1, 3, 5, 7])

In [19]:
c = np.linspace(0, 1, 6)#starts at 0, ends at 1, with 6 points 
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
d = np.linspace(0, 1, 5, endpoint=False)#starts a 0, ends at 1, with 5 points, but ending point is exclusive
d

array([0. , 0.2, 0.4, 0.6, 0.8])

In [23]:
a = np.ones((3,3))#creates an array filled with 1s with 3 rows x 3 col
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
b = np.zeros((2,2)) #creates an array filled with 0s 2 rows x 2 col
b

array([[0., 0.],
       [0., 0.]])

In [30]:
c = np.eye(3)#3 rows x 3 col with the middle diagonal filled with 1s and the rest 0s
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
d = np.diag(np.array([1,2,3,4]))# fills the diagonal with specified array 
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [36]:
a = np.random.rand(4) #creates an array with 4 elements of random value ; values between 0-1
a

array([0.19525297, 0.4496796 , 0.46197666, 0.45551813])

In [38]:
b = np.random.randn(4)#randn includes negative values 
b

array([ 0.86634573,  0.38223251,  0.37497847, -1.2172588 ])

In [39]:
np.random.seed(1234)  

Create different kinds of arrays with random numbers.

In [43]:
#creates a 5x4 array filled with random values
np.random.rand(5,4)

array([[0.36488598, 0.61539618, 0.07538124, 0.36882401],
       [0.9331401 , 0.65137814, 0.39720258, 0.78873014],
       [0.31683612, 0.56809865, 0.86912739, 0.43617342],
       [0.80214764, 0.14376682, 0.70426097, 0.70458131],
       [0.21879211, 0.92486763, 0.44214076, 0.90931596]])

Try setting the seed before creating an array with random values.

In [47]:
np.random.seed(4321)
array2 = np.random.rand(5,4)
array2

array([[0.07080288, 0.81506401, 0.76790496, 0.2863545 ],
       [0.19309431, 0.97891221, 0.40622871, 0.75776787],
       [0.08915177, 0.30988347, 0.61892762, 0.45991048],
       [0.21830943, 0.66352023, 0.6786827 , 0.95031851],
       [0.28126114, 0.6198517 , 0.38329512, 0.40036072]])

In [50]:
np.random.seed(4321)
array2 = np.random.rand(5,3)
array2

array([[0.07080288, 0.81506401, 0.76790496],
       [0.2863545 , 0.19309431, 0.97891221],
       [0.40622871, 0.75776787, 0.08915177],
       [0.30988347, 0.61892762, 0.45991048],
       [0.21830943, 0.66352023, 0.6786827 ]])

Look at the function np.empty. What does it do? When might this be useful?

In [54]:
#np.empty creates an array with really extreme values but shape you choose
#extreme values act as place holders for you to input data into them
array3 = np.empty([3,3])
array3

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.10077826e-320],
       [1.42644408e-153, 2.44150666e-154, 4.56335201e-072]])

# Lecture 5.2

### Agenda:

- Programming questions
- Dr. Coupe will show some plots 
- Examples of for loops

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [4]:
#set random seed 
np.random.seed(1250)

In [7]:
#randint gives you a random integer within a specifec range 
np.random.randint(1,5)

2

In [10]:
#for x in range(100)
#goes through 1-100?

In [24]:
#you can use max to set limits 
a = [10] #starting value 

for x in range(20):#will go through it 20 times 
    p = np.random.randint(1,4)
    y = a[-1]
    if p == 3:
        y = min(5, y - 1)#y never goes below 5 when you decrease it 
    else:
        y = y + 1 
        #y = max(30, y + 1)
    a.append(y)
        
print(a)
    

[10, 11, 12, 13, 5, 6, 7, 5, 6, 5, 6, 7, 8, 9, 10, 11, 12, 13, 5, 4, 5]


### Congratulations! ¡Felicidades! You finished Intermediate Python!