Name: Kara Eckley

Labpartner(s): Luz Ballesteros

In [2]:
# import statements go here
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [2]:
#1.4.1.2 Creating Arrays

#1D array
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [3]:
a.ndim

1

In [4]:
a.shape

(4,)

In [5]:
len(a)

4

In [6]:
#2D array
b = np.array([[0, 1, 1], [3, 4, 5]])
b

array([[0, 1, 1],
       [3, 4, 5]])

In [7]:
b.ndim

2

In [8]:
b.shape

(2, 3)

In [9]:
len(b)

2

In [11]:
#3D array
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [12]:
c.shape

(2, 2, 1)

In [13]:
c.ndim

3

In [22]:
len(c)

2

In [18]:
#My 2D array
d = np.array([[9, 7, 5, 3, 1], [0, 2, 4, 6, 8]])
d

array([[9, 7, 5, 3, 1],
       [0, 2, 4, 6, 8]])

In [19]:
len(d)

2

In [20]:
np.shape(d)

(2, 5)

In [21]:
d.ndim

2

In [ ]:
# My 2D array has 2 dimensions, 2 rows, and 5 columns, which also helps to describe it's shape.

In [23]:
#Functions for creating arrays

#Evenly spaced
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b = np.arange(1,9,2)
b

array([1, 3, 5, 7])

In [25]:
#By number of points
c = np.linspace(0,1,6)
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [26]:
d = np.linspace(0,1,5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

In [27]:
#Common arrays
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [29]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [31]:
#Random numbers
a = np.random.rand(4)
a

array([0.4511515 , 0.39837692, 0.80512149, 0.83219482])

In [32]:
b = np.random.randn(4)
b

array([-1.04352846, -1.32362954,  1.01213807, -0.09782078])

In [33]:
np.random.seed(1234)

In [36]:
#Practice/Experimenting
x = np.array([np.arange(0,100,5)])
x

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75,
        80, 85, 90, 95]])

In [38]:
y = np.linspace(100, 1000, 25)
y

array([ 100. ,  137.5,  175. ,  212.5,  250. ,  287.5,  325. ,  362.5,
        400. ,  437.5,  475. ,  512.5,  550. ,  587.5,  625. ,  662.5,
        700. ,  737.5,  775. ,  812.5,  850. ,  887.5,  925. ,  962.5,
       1000. ])

In [40]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [46]:
np.diag((7,2))

array([[7, 0],
       [0, 2]])

In [47]:
z = np.array([np.random.rand(5)])
z

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581]])

In [48]:
l = np.array([np.random.randn(10)])
l

array([[-0.94029827, -0.95658428, -0.33060682,  0.87412791,  2.00254961,
         0.01086208, -0.86924706,  1.4249841 ,  0.1458091 ,  2.89409095]])

In [49]:
np.random.seed(563)

In [50]:
z = np.array([np.random.rand(5)])
z

array([[0.80709064, 0.13668307, 0.70480303, 0.01265657, 0.34077069]])

In [51]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C')

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the given shape, dtype, and
    order.  Object arrays will be initialized to None.

See Also
--------
empty_like : Return an empty array with shape and type of input.
ones : Return a new array setting values to one.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Notes
-----
`empty`, unlike `zeros`, does not set the array values to ze

In [ ]:
#It seems to me that np.empty gives you the structure for an array of a given shape, which you can then fill with your own input for whatever use. This could be useful if you're having trouble formatting arrays or working with large arrays.

# Lecture 5.2

### Agenda:

- Programming questions
- Dr. Coupe will show some plots 
- Examples of for loops

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

Code Notes!

np.random.seed() - sets the random seed, which allows for reproducibility of results.
np.random.rand() - if no argument, a random integer is chosen from between 0-1.
np.random.randint() - used to select random integers within a given range.
np.transpose() - 
range() - used in performing a simulation a certain number of times
max() - to set a maximum limit in a loop
plt.hist() - to plot a histogram

In [6]:
#Practice

a = np.random.randint(20)
a

13

In [7]:
b = np.array([np.random.rand(20)])
b

array([[0.05428432, 0.53297688, 0.65909444, 0.72954926, 0.86985607,
        0.27025281, 0.27999434, 0.62522877, 0.84191916, 0.34301366,
        0.19573217, 0.23137393, 0.51042908, 0.90919591, 0.89042003,
        0.25925481, 0.05204903, 0.29296386, 0.89100854, 0.35238801]])

In [8]:
b[b>0.5]

array([0.53297688, 0.65909444, 0.72954926, 0.86985607, 0.62522877,
       0.84191916, 0.51042908, 0.90919591, 0.89042003, 0.89100854])

In [20]:
c = np.linspace(0,25,25)
d = []

In [21]:
for element in c:
    if element > 15:
        d.append(element +10)

In [22]:
d

[25.625,
 26.666666666666668,
 27.708333333333336,
 28.75,
 29.791666666666668,
 30.833333333333336,
 31.875,
 32.91666666666667,
 33.958333333333336,
 35.0]

In [24]:
e = np.ones((5,5))
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
f = np.zeros((1))
f

array([0.])

In [34]:
g = np.diag((1,2,3,4,5))
g

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [36]:
h = g[g >= 1]
h

array([1, 2, 3, 4, 5])

In [40]:
number =15
for element in h:
    if number <10:
        number = number -2
        print("try again")
    else:
        print("not today")

not today
not today
not today
not today
not today


### Congratulations! ¡Felicidades! You finished Intermediate Python!