Name: Kara

Labpartner(s): Dwight

In [49]:
#import statements go here
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Class 8.2

# Warmups 8.2

Music to code loops by (featuring samples of Warf and Geordi from Star Trek TNG). Mobius by Orbital:

https://www.youtube.com/watch?v=4PG5PCd284o.

(I was this many years old when I learned you could stick a period at the end of the youtube url to suprress the ads, try it)

Let's keep practiciing functions and logical control. Raise your hand when you get confused, and look at the suggested solutions, this is tricky stuff to master.


**W.1** Do Practice Python 28, Max of Three https://www.practicepython.org. 

Suggested approach: Writing some notes on how you will code something before you begin is really helpful and standard practice. Write some pseudocode to think out the problem before you begin. Here are some examples of this: https://www.unf.edu/~broggio/cop2221/2221pseu.htm  

https://www.youtube.com/watch?v=HhBrkpTqzqg

We'll do more of this in lab, but give it a shot here.

I'm going to try to compare the variables in pairs using >, < statements, and have the largest number be returned at the end.

In [2]:
a = 3
b = 9
c = 4

In [36]:
def largestvariable(a, b, c):
    if np.logical_and(a>=b, a>=c):   
        print("a")
    elif b>=c:
        print("b")
    else:
        print("c")

In [37]:
largestvariable(a, b, c)

b


In [38]:
a = 24
b = 1
c = 1000043

In [39]:
largestvariable(a, b, c)

c


In [40]:
a = 6
b = 6
c = 4

In [41]:
largestvariable(a, b, c)

a


In [15]:
np.logical_and?

Call signature:  np.logical_and(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'logical_and'>
File:            c:\users\kara\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
logical_and(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Compute the truth value of x1 AND x2 element-wise.

Parameters
----------
x1, x2 : array_like
    Input arrays. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the

# Lecture 8.2

### Agenda:

- Syllabus changes
- CV Assignement
- Questions
- (if time) pseudocode example

### Syllabus changes

New Syllabus is up on BB. Here is the grading changes (changes in **BOLD**)

To receive an A grade, students must
-	Meet the specifications for receiving a B grade
-	Satisfactorily complete all advanced labs

To receive a B grade, students must
-	Meet the specifications for receiving a C grade
-	Satisfactorily complete **one out of three** advanced labs

To pass the course with a C, students must
-	Meet the specifications for receiving a D grade 
-	Satisfactorily complete the Linear Regression, Timeseries Analysis and **History of Hacking** labs
-	Provide satisfactory course feedback

To pass the course with a D, students must 
-	Satisfactorily complete all assigned chapters in datacamp **and the associated labs, as well as Cartopy and Movies lab**
-	Satisfactorily complete all components of the final project

Failure to deliver a satisfactory final assignment will result in an F, regardless of other assignments done.

### New Schedule
![](revised_schedule.png)

### CV assignment, Word and Zotero integration assignment (turn these in with Lab 8.2)

- Demo of Overleaf
- Demo of Zotero and Word
- Demo of Zotero and Overleaf

Assignement:

You will make a CV in Overleaf using the LaTex typesetting software. Pick a CV template and modify it to have your info. Make sure you include a picture (required, this is to get you used to the syntax for this). Don't get overwhelmed by all the detailed code, just figure out what you need to modify to put in your information.

You will submit a word document that is integrated with zotero and features three references. Submit both the document file, and a screenshot of your zotero account with the references in it.

Extra Credit (2 assignment tokens):
Integrate Overleaf and Zotero. There are two ways to do this, you can integrate zotero directly into overleaf (but I think they charge for this now) or you can export your citations from zotero as a .bib file and upload this into Overleaf. If you're keen, give it a shot! 


In [ ]:
#I managed to intergrate Overleaf and Zotero! Instead of the publications section originally on the CV template, I changed it so a "Zotero References" section to display the same references.

### Questions

# Lab 8.2

**E.1** Go through the following tutorial on pseudocode and logical control. They are coding in a different language (I think C++). You will translate what they did into python. You can do it!

https://www.youtube.com/watch?v=PwGA4Lm8zuE

Make sure you write your notes out here with your pseudocode. Take your time and think it through

May be good to capitilize code.
One statement per line.
Indent!
Specificity.

The Instructions. Prints 1 - 20. Multiple of 3 print "Fizz", of 5 print "Buzz", of 3 and 5 print "FizzBuzz".

Initialize a for loop. End the loop at 20. Count in intervals of 3. Use function to check remainder of numbers if divisible by 3, 5, or both. Add print statements with the corresponding word, or print the number if not divisible by any of our numbers.

In [44]:
numbers = np.arange(1,21)

In [45]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
for x in numbers:
    if (x%15 == 0):
        print("FizzBuzz")
    elif (x%3 == 0):
        print("Fizz")
    elif (x%5 ==0):
        print("Buzz")
    else:
        print(x)
    

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz


**E.2** Complete Data Manipulation with pandas Ch 2 in datacamp.


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

.mean, to median, .mode, .min, .max, .var, .std, .quantile- all used to find basic stats of your data.
.agg - method to apply function or functions to multiple columns at a time.
.drop_duplicates - gets rid of duplicate row to only have one of each type.
.value_counts - counts values
.groupby - groups data by a certain variable for further use/analysis
.pivot_table - shows data by two variables in a table, can count and sum it up by both variables
fill_values - replaces NaN with a specified value, usually 0
margins - used in pivot tables for totaling rows and columns

### This week's project:

This week we will be doing a CV assignment in LaTeX. Make your CV in LaTeX using Overleaf or the LaTeX interface of your choice (Word is not an option!!). You might find a cool template

In [ ]:
#Practice

In [51]:
a = np.random.randint(0,10,10)
a

array([9, 4, 7, 3, 5, 1, 5, 4, 4, 9])

In [52]:
a+a

array([18,  8, 14,  6, 10,  2, 10,  8,  8, 18])

In [71]:
b = np.random.randint(0,10,10)
b

array([6, 0, 3, 1, 6, 2, 6, 5, 5, 4])

In [62]:
np.tile([a, b], 2)

array([[9, 4, 7, 3, 5, 1, 5, 4, 4, 9, 9, 4, 7, 3, 5, 1, 5, 4, 4, 9],
       [6, 6, 7, 9, 2, 4, 0, 6, 2, 7, 6, 6, 7, 9, 2, 4, 0, 6, 2, 7]])

In [64]:
a.mean()

5.1

In [73]:
c = 2, 6, 3, 8, 4, 2, 3, 3, 7, 9

In [76]:
c.describe

AttributeError: 'tuple' object has no attribute 'describe'

In [78]:
a.pd.DataFrame()

AttributeError: 'numpy.ndarray' object has no attribute 'pd'

In [79]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: Union[Collection, NoneType] = None,
    columns: Union[Collection, NoneType] = None,
    dtype: Union[str, numpy.dtype, ForwardRef('ExtensionDtype'), NoneType] = None,
    copy: bool = False,
)
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, or list-like objects.

    .. versionchanged:: 0.23.0
       If data is a dict, column order follows insertion-order for
       Python 3.6 and later.

    .. versionchanged:: 0.25.0
       If data is a list of dicts, column order follows insertion-order
       for Python 3.6 and later.

index : Ind

In [80]:
d = [2, 4, 2, 4]
e = [1, 3, 1, 3]

In [81]:
d?

Type:        list
String form: [2, 4, 2, 4]
Length:      4
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [82]:
np.array(d)

array([2, 4, 2, 4])

In [83]:
np.array(e)

array([1, 3, 1, 3])

In [91]:
f = np.tile([d,e], 2)

In [95]:
f

array([[2, 4, 2, 4, 2, 4, 2, 4],
       [1, 3, 1, 3, 1, 3, 1, 3]])

In [96]:
g = pd.DataFrame(f)

In [97]:
g.describe

<bound method NDFrame.describe of    0  1  2  3  4  5  6  7
0  2  4  2  4  2  4  2  4
1  1  3  1  3  1  3  1  3>

In [99]:
g.mean()

0    1.5
1    3.5
2    1.5
3    3.5
4    1.5
5    3.5
6    1.5
7    3.5
dtype: float64