Name: Kara Eckley

Labpartner(s): Adam

In [64]:
#import statements go here
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Class 7.1

Hope everyone is recovering from the freeze. Being in survival mode is stressful! I am going to attemt to be easy on you this week. As announced, there are no labs assigned last week, we are just taking a pass on those. I may have to shuffle some of the later material in the schedule, TBD.

I am having special office hours tomorrow, Tuesday 2-3 on the class zoom channel. I am asking those of you who are behind on any labs to check in with me and make a plan. If you can't make that time, let's schedule another one ASAP. Please note that you cannot miss these early labs and pass the class, and the material builds, so it is critical we get you caught up.


This week we are going to do more plotting, learn about functions, and apply this to your datasets. Next Monday we will have present your work day again, see below for details. Hopefully at this point the material is building to the point where it is not all forein and you will feel a bit more confident.

Originally we had introduction of Zotero and a CV assignment on the schedule for this week, but I'm pushing that until next week so we have less new material to deal with this week.

# Warmups 7.1

**W.1** Go through 1.4.1.5 Indexing and Slicking in the scipy lecture notes, up to the exercises, which you will do on Wednesday. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a[0], a[2], a[-1]

(0, 2, 9)

In [6]:
#Multidimensional arrays
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [7]:
a[1,1]

1

In [10]:
a[2,1] = 10
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [11]:
a[1]

array([0, 1, 0])

In [12]:
#Slicing
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[2:9:3]

array([2, 5, 8])

In [14]:
a[:4]

array([0, 1, 2, 3])

In [15]:
a[1:3]

array([1, 2])

In [16]:
a[::2]

array([0, 2, 4, 6, 8])

In [17]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
a = np.arange(10)

In [20]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [21]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [22]:
#Indexing and slicing
np.arange(6) + np.arange (0,51,10)[:,np.newaxis]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [25]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [30]:
np.linspace(11,1,6)

array([11.,  9.,  7.,  5.,  3.,  1.])

In [34]:
c = np.ones((4,4))

In [37]:
c[2,3] = 2
c[3,1] = 6
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 2.],
       [1., 6., 1., 1.]])

In [45]:
d = np.zeros((6,5))
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
d[1,0]= 2
d[2,1]= 3
d[3,2]= 4
d[4,3]= 5
d[5,4]= 6
d

array([[0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 6.]])

In [47]:
np.tile?

Signature: np.tile(A, reps)
Docstring:
Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat e

In [57]:
a = np.array([[4,3], [2,1]])

In [66]:
np.tile(a, (2,3))

array([[4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1]])

# Lecture 7.1

### Agenda:

- The Parable Of Finding Nemo, or How To Do The Seemingly Impossible
- Questions
- Functions!


### Questions

### Functions

Functions are super-useful for doing repetative tasks. You have been using pre-defined functions constantly, when you define arrays, make a plot, or analyse data. Now you are going to learn to write your own.

For more information on functions and documenting:
- http://scipy-lectures.org/intro/language/functions.html?highlight=functions
- https://realpython.com/documenting-python-code/


Basic syntax:

In [35]:
# first you define the function

def function_name():
    # some code that does something
    print('Inside the function')

In [36]:
# then you call the function
function_name()

Inside the function


Note that defined funtions show up using whos

In [37]:
whos

Variable        Type         Data/Info
--------------------------------------
Height_Change   function     <function Height_Change at 0x000002332D767790>
data            DataFrame           Video Treatment An<...>n\n[49 rows x 27 columns]
function_name   function     <function function_name at 0x000002332D767E50>
np              module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
pd              module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
plt             module       <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>


That's a really useless function, let's make a better one.

In [38]:
# usually you want to pass a varible of some sort to the function to manipulate

def circle_area(radius):
    area = 3.14*radius**2
    return area   # the return statement means that the function will return that variable

In [39]:
circle_area(5)

78.5

What happens if I don't add the required input?

In [40]:
circle_area()

TypeError: circle_area() missing 1 required positional argument: 'radius'

What happens if I omit the return statement?

In [41]:
def circle_area(radius):
    area = 3.14*radius**2

How do I save the function output to a variable?

In [42]:
def circle_area(radius):
    area = 3.14*radius**2
    return area

In [43]:
x = circle_area(5)

Does the area variable inside the function exist outside of it?

In [45]:
x

78.5

Note I also could have made my function like this:

In [46]:
def circle_area4(radius):
    return 3.14*radius**2

In [47]:
circle_area4(5)

78.5

### Parsing for bad imput

Note my above function will work even if the input is negative, which is not reasonable. So I probably want to include a statement that checks if the input is weird.

In [48]:
def circle_area5(radius):
    
    # put in an if statement to handle bad inputs
    
    
    return 3.14*radius**2

In [49]:
circle_area5(-3)

28.26

In [50]:
circle_area5(3)

28.26

### Using packages within functions

We can also have import statements within a function, but this can slow the function down if the package is not loaded already

In [51]:
def circle_area6(radius):
    import numpy as np
    
    return np.pi*radius**2

In [52]:
circle_area6(3) # note this is a much more accurate

28.274333882308138

We can have the function inputs have pre-defined default values, so that if you don't pass a variable it will use the default

In [53]:
def circle_area7(radius = 3):
    import numpy as np #import numpy so we can use the more exact value of pi
    
    return np.pi*radius**2

In [54]:
circle_area7() # no argument given, so uses radius = 3 by default

28.274333882308138

Is numpy imported outside the function? Let's check

In [55]:
# can our function handle lists? Let's check
r = [1,2,3]
circle_area7(r)



TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [56]:
# can our function handle arrays?

rnp = np.array(r)
circle_area7(rnp)

# what type of variable did the function return?

array([ 3.14159265, 12.56637061, 28.27433388])

### It is very useful to add some documentation string info to your functions

In [57]:
def circle_area7(radius = 3):
    """ Returns the area of a circle given the radius. 
    Assumes the radius is 3 if not supplied. """
    import numpy as np
    
    return np.pi*radius**2

Now my note in the triple quotes shows up as a docstring

In [58]:
circle_area7?

Signature: circle_area7(radius=3)
Docstring:
Returns the area of a circle given the radius. 
Assumes the radius is 3 if not supplied. 
File:      c:\users\kara\documents\utrgv\year 1\spring\mars 5170\<ipython-input-57-a636b96954d7>
Type:      function


There is a standard practice in programming to write out the Parameters (inputs/arguments) and Returns (output) in the docstring. Let's look a this for a predefined function and then make if for our simple function.

In [59]:
import numpy as np

In [60]:
np.max?

Signature:
np.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See `ufuncs-output-type` for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is passed

In [61]:
def circle_area7(radius = 3):
    """ Returns the area of a circle given the radius. 
    
    Parameters
    ----------
    radus: array like, radius of the circle
    Assumes the radius is 3 if not supplied.
    
    Returns
    -------
    area: ndarray or scalar
    Returns the area for the given radii
    
    """
    
    import numpy as np
    
    return np.pi*radius**2

In [62]:
circle_area7?

Signature: circle_area7(radius=3)
Docstring:
Returns the area of a circle given the radius. 

Parameters
----------
radus: array like, radius of the circle
Assumes the radius is 3 if not supplied.

Returns
-------
area: ndarray or scalar
Returns the area for the given radii
File:      c:\users\kara\documents\utrgv\year 1\spring\mars 5170\<ipython-input-61-93255415a260>
Type:      function


# Lab 7.1

**E.1** Complete Introduction to Data Visualization with Matplotlib Chapters 1-2


**E.2** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

plt.subplots = to crease subplots on the figure
plt.show = to show the figure. Required on datacamp - not on jupyterlab
ax.plot - setting axes for the figure. linestyle, color, and marker can all used with ax.plot to customize figures.
ax.set(x, y_label, or title) - used to add labels to axes/figures.
parse_dates and index_col - used to sort/parse through date columns
ax.twinx - put two functions on the same graph with different y axis
def - used to define a function
annotate - used to annotate or mark a location in a figure with relevant information
pd.Timestamp - used to refer to a location in annotation

### This week's project:

For Monday's class you will write two functions that work on your dataset (you can use the same dataset or a different one). The first function will do some sort of analysis, manipulation or calculation, the second will be a plotting function. The idea here is that if you had another datafile that was similar, you could use the function to do the operation again easily.

**E.3** Write one or more functions that manipulate your dataset and do some sort of analysis. You will present these to the class on Monday.

In [67]:
data = pd.read_csv('Anemone Data2.csv')

In [68]:
data

Treatment Anemone  StartDiameter  EndDiameter
0        32C       1           1.53         1.56
1        NaN       2           0.69         0.69
2        NaN       3           0.89         0.93
3        NaN       4           0.93         0.85
4        32C       1           0.69         0.71
5        NaN       2           0.75         0.91
6        NaN       3           0.70         0.71
7        NaN       4            NaN          NaN
8        25C       1           0.55         0.70
9        NaN       2           0.88         1.07
10       NaN       3            NaN          NaN
11       NaN       4           1.15         1.12
12       25C       1           0.72         0.68
13       NaN       2           1.27         1.22
14       NaN       3           0.86         0.89
15       NaN       4           1.06         0.98
16       40C       1           0.59         0.67
17       NaN       2            NaN          NaN
18       NaN       3            NaN          NaN
19       NaN       4           0.70         0.83
20       40C       1           0.76         0.69
21       NaN       2           1.00         1.17
22       NaN       3           0.65         1.09
23       NaN       4           0.85         0.97
24       NaN       5           0.69         0.82
25       32E       1           0.72         0.36
26       NaN       2           0.60          NaN
27       NaN       3           0.89         0.83
28       NaN       4           0.79         0.30
29       32E       1            NaN          NaN
30       NaN       2            NaN          NaN
31       NaN       3           0.85         0.42
32       NaN       4           0.56         0.73
33       25E      1*           1.15         1.00
34       NaN       2           0.81         0.51
35       NaN       3           0.79         0.45
36       NaN       4           1.06         0.37
37       25E       1           0.87         0.77
38       NaN       2           1.27         0.51
39       NaN       3           0.97         0.54
40       NaN       4           1.11         1.03
41       40E       1           0.90         0.73
42       NaN       2           0.77          NaN
43       NaN       3           1.12         0.85
44       NaN       4           0.85         0.83
45       40E       1           0.94         0.43
46       NaN       2           0.73         0.52
47       NaN       3           1.11         0.82
48       NaN       4           1.07         0.40

In [88]:
anemonedata = (data['StartDiameter'], data['EndDiameter'])

In [89]:
anemonedata_np = np.array(anemonedata)

In [101]:
anemonedata_np

array([[1.53, 0.69, 0.89, 0.93, 0.69, 0.75, 0.7 ,  nan, 0.55, 0.88,  nan,
        1.15, 0.72, 1.27, 0.86, 1.06, 0.59,  nan,  nan, 0.7 , 0.76, 1.  ,
        0.65, 0.85, 0.69, 0.72, 0.6 , 0.89, 0.79,  nan,  nan, 0.85, 0.56,
        1.15, 0.81, 0.79, 1.06, 0.87, 1.27, 0.97, 1.11, 0.9 , 0.77, 1.12,
        0.85, 0.94, 0.73, 1.11, 1.07],
       [1.56, 0.69, 0.93, 0.85, 0.71, 0.91, 0.71,  nan, 0.7 , 1.07,  nan,
        1.12, 0.68, 1.22, 0.89, 0.98, 0.67,  nan,  nan, 0.83, 0.69, 1.17,
        1.09, 0.97, 0.82, 0.36,  nan, 0.83, 0.3 ,  nan,  nan, 0.42, 0.73,
        1.  , 0.51, 0.45, 0.37, 0.77, 0.51, 0.54, 1.03, 0.73,  nan, 0.85,
        0.83, 0.43, 0.52, 0.82, 0.4 ]])

In [107]:
np.shape(anemonedata_np)

(2, 49)

In [117]:
def Diameter_Change(row_of_anemone):
    Diameter_Change = (anemonedata_np[0,row_of_anemone])-(anemonedata_np[1,row_of_anemone])
    return Diameter_Change

#This function calculates the change in anemone diameter during a several minute experiment when they were exposed to a stress pheremone.
#Parameters: The columns are the start and end diameter of the anemone's oral disk.
#Returns: The change in diameter during the experiment

In [115]:
Diameter_Change(45)

0.51

In [116]:
Diameter_Change(2)

-0.040000000000000036

In [98]:
anemonedata_np?

Type:            ndarray
String form:    
[[1.53 0.69 0.89 0.93 0.69 0.75 0.7   nan 0.55 0.88  nan 1.15 0.72 1.27
           0.86 1.06 0.59  nan  na <...> nan 0.42 0.73 1.   0.51 0.45 0.37 0.77 0.51 0.54 1.03 0.73
           nan 0.85 0.83 0.43 0.52 0.82 0.4 ]]
Length:          2
File:            c:\users\kara\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For m

**E.4** If you haven't yet, complete the introductions assignment on slack (add the channel, introduce yourself)

In [ ]:
#Done