Name: Kara Eckley

Labpartner(s): Adam

In [62]:
# import statements go here

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Class 5.1

## Monday labs are due Thursday at midnight

Today you all are going to do the lecture! It's Present Your Plots Day.

# Warmups 5.1

### Warmup is short today (20 min) so we have time to focus on your plots.

**W.1** Do Exercise 3 in practice python https://www.practicepython.org

In [14]:
np_numbers = np.array([2, 6, 7, 3, 7, 8])

In [15]:
np_numbers[np_numbers <5]

array([2, 3])

In [18]:
#Enter a number below
Number = 8

In [19]:
np_numbers[np_numbers < Number]

array([2, 6, 7, 3, 7])

# Lecture 5.1

## Agenda:

- Questions about class or coding
- Review of assignment tokens system
- Show us your plots! Explain your data set, what you did with it, and what your learned, including any difficulties you had and how you solved them.

## Assignment Tokens review

### From syllabus:

Each student will begin the semester with ten assignment tokens, which they can use to miss a lab meeting, an assessment exercise, resubmit an unsatisfactory assignment or turn an assignment in late.

### From: 4.1.1 How to earn more assingment tokens

Studies show students at all levels like gamification. So let’s try this. We are going to institute an assignment token earning system starting next wek. There will be awards for having lots of tokens…and a winner...and prizes. 

Earn assignment tokens for: 
- Doing the data camp chapter before class (1 token)
- Turning in Monday’s lab by Tuesday at midnight (1 token)
- Creating a cool demo or exercise for your classmates (1+ tokens, depending on awesomeness)
- Creating warmup exercises (1+ tokens, depending on how many, quality, etc.)

To earn your tokens, send me and Adrian your proof, code, etc. over slack. That is, in a group message to both Adrian and I.

As always, let me know in your weekly assessments if you have ideas on how to improve this game.



# Lab 5.1

**E.1** Complete intermediate python chapter 4: Loops

Note that loops often are very confusing for new programmers, but they are very powerful and super-useful. You will be seing them again.

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/IntroSciComp_S2021/blob/main/Class_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You might use the resources linked above for supplementary examples. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

while - used to continue to run a code on loop so long as the conditions are true
for - can be used to apply a function to each variable in a sequence
enumerate - used in "for", prints out index as well as values
.items() - a method used to on dictionaries to print out each value similarly to enumerate
np.nditer() - used to for iteration on numpy arrays, particularly 2D arrays
.iterrows() - same but for DataFrames
.apply() - used to add a column to a DataFrame

**E.3-6** Exercises 4-7 in practice python (see link above)

In [80]:
#Exercise 4

#Enter a number below
number = 10

In [81]:
x = np.arange(1, number+1, 1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
number % x

array([0, 0, 1, 2, 0, 4, 3, 2, 1, 0], dtype=int32)

In [85]:
x[(number%x)<1]
##### IT WORKED!!!!!!!!

array([ 1,  2,  5, 10])

In [95]:
#Exercise 5

a = [1, 3, 6, 8, 9, 13, 78, 102]
b = [5, 6, 9, 32, 53, 78]
y = []

In [96]:
for element in a and b:
    if element in a and b:
        y.append(element)

In [97]:
y

[6, 9, 78]

In [115]:
#Exercise 6

#Type a string below
Strings = 'palindrome'

In [116]:
if Strings[::-1] == Strings:
    print("Yeah, I think it is!")
else:
    print("Nice try, but no.")

Nice try, but no.


In [126]:
#Exercise 7

a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
b = []

In [131]:
for element in a:
    if element%2 <1:
        b.append(element)

In [132]:
b

[4, 16, 36, 64, 100]