Name

Labpartner(s)

In [6]:
#import statements go here
import numpy as np


# Class 9.2

# Warmups 9.2

It was so much fun working together on Monday we will do it again. Spend 15 min working on the following and then we will go over it together:

**W.1** Write a function that returns the first n consectutive odd intergers (ex: 1,3,5,7,9 for n = 5) using only logical control (i.e. don't use indexing short cuts to make the odd integers, only for or while loops)

In [3]:
def oddnum():
    num = int(input("Enter a numer:"))
    
    a=0
    b=1
    if (num <= 0):
        return "Error: you must input a positive non-zero number"
    

In [7]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [4]:
#Make consecutive odd number
# input n which will be use for counter   counter= how many executions
                                                           #Some kind of loop

def oddnumb(counter):
    start = 1
    n= 5 
    my_list =[start] 
    while n>1:
        n= n-1
        next_num= start + 2
        my_list = my_list + [next_num]                #add the resulting number to my_list
        print(my_list)

        new_number = next_num

In [5]:
def oddnum(n)K:
    x=1
    y=[]
    t =1
    while t<=n:
        y.append[n]
        x= x + 1
    return y

SyntaxError: invalid syntax (<ipython-input-5-81463cc58488>, line 1)

In [ ]:
oddnum(3)

**Extra:** Modify your function so that it can start anywhere. That is, add a second input that gives a starting integer. Ex: 7,9,11 for n = 3 and a starting value of 7

In [15]:
a=[2]
b=[2]
a.append(b)
a

[2, [2]]

# Lecture 9.2

### Agenda:
- Research project assignment and what is due this week
- Links to previous class githubs are in our github in the resources document in the Course Materials folder: https://github.com/chsharrison/IntroSciComp_S2021/blob/main/Class_materials/resources.md

#### Reminders
- Many of you need to make up "show us your functions" we will do this in office hours or by appointment. I want to make sure everyone gets this function syntax down. See column in BB for above. Many of you need to redo this.
- To get tokens for turning in labs or finishing datacamp chapters early, you need to send me and Adrian a message on slack (see instructions I gave you, on blackboard and in previous labs). We won't notice unless you tell us to look.

### Questions

# Lab 9.2

**E.1** Complete Data Manipulation with pandas Ch 4 in datacamp.


**E.2** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

### This week's project:

This week you will be doing two things, planning on what grade you will get in this course (due Thursday with lab 9.1) and submitting your research topic (due Sunday with lab 9.2). 

**E.4** Write a few sentances about what you plan to do for your research project. See tab in BB to turn this in

Practice

In [7]:
import numpy as np
num=np.arange(10,20,5)
print(num)

[10 15]


In [6]:
import numpy as np
num=np.arange(10,20+5,5)
print(num)

[10 15 20]


In [16]:
import numpy as np
c = np.ones((10,10))  # reminder: (3, 3) is a tuple

c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
c[1,2]=2     #second, 3rd column
c



array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
c[1,]=3 #all 2nd rows
c

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
c[4,:]= 5       #5th row all
c
 



array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
c[:,4]= 5      #all 5th row
c 

array([[1., 1., 1., 1., 5., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 5., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 5., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 5., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 5., 1., 1., 1., 1., 1.]])