In [3]:
import numpy as np
import pandas as pd

In [4]:
a = np.arange(10)
a

a[0], a[2], a[-1]

(0, 2, 9)

In [5]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [6]:
a[2, 1] = 10 # third line, second column
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [7]:
run_record=[3,6,7,8]
run_record

[3, 6, 7, 8]

In [9]:
nprun=np.array(run_record)
nprun

array([3, 6, 7, 8])

In [10]:
nprun.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [12]:
print(nprun.mean)

<built-in method mean of numpy.ndarray object at 0x000002975B7995D0>


In [13]:
run_record.mea

AttributeError: 'list' object has no attribute 'mean'

In [14]:
run_record.append = "zedric"

AttributeError: 'list' object attribute 'append' is read-only

In [15]:
run_record.append("zedric")

In [16]:
run_record

[3, 6, 7, 8, 'zedric']

In [17]:
nprun

array([3, 6, 7, 8])

In [18]:
np.append(nprun["Zedric"])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [19]:
np.mean(nprun)

6.0

In [21]:
np.std(nprun)

1.8708286933869707

In [22]:
np.min(nprun)

3