Name

Labpartner(s)

In [1]:
#import statements go here
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Lab 4.2 

Wednesday labs are due Sunday at midnight

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner in your breakout room, they are your partner for this lab. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Blackboard.

# Warmups 4.2

W.1-3 Do exercises 1-3 in http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 4.1  on how to load in the data file

In [3]:

data = np.loadtxt('populations.txt')
year, hares, lynxes, carrots = data.T
populations = data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [4]:
print("         Hares, Lynxes, Carrots")
print("Mean:", populations.mean(axis=0))
print("Std:", populations.std(axis=0))

         Hares, Lynxes, Carrots
Mean: [34080.95238095 20166.66666667 42400.        ]
Std: [20897.90645809 16254.59153691  3322.50622558]


In [5]:
hare_mean = np.mean(data[: ,1])
hare_mean

34080.95238095238

In [6]:
lynx_mean = np.mean(data[: ,2])
lynx_mean

20166.666666666668

In [7]:
carrot_mean = np.mean(data[: ,3])
carrot_mean

42400.0

In [11]:
hare = np.max(data[0:21]) ## 1903 and hare 
hare

77400.0

In [12]:
np.where(hare == 77400)

(array([0], dtype=int64),)

In [18]:
years = data[:,0]
years

years[3]

1903.0

In [22]:
data1 = data[:,1:4]
data1

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [23]:
np.argsort(data1)


array([[1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [0, 2, 1],
       [0, 2, 1],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 2, 0],
       [1, 2, 0],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2],
       [0, 1, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]], dtype=int64)

In [26]:
max_species = np.argmax(data1, axis = 1)

In [28]:
species = np.array(['Hare', 'Lynx', 'Carrot'])
max_species1 = species[max_species]
maxpopulation = np.column_stack((years, max_species1))
maxpopulation

array([['1900.0', 'Carrot'],
       ['1901.0', 'Carrot'],
       ['1902.0', 'Hare'],
       ['1903.0', 'Hare'],
       ['1904.0', 'Lynx'],
       ['1905.0', 'Lynx'],
       ['1906.0', 'Carrot'],
       ['1907.0', 'Carrot'],
       ['1908.0', 'Carrot'],
       ['1909.0', 'Carrot'],
       ['1910.0', 'Carrot'],
       ['1911.0', 'Carrot'],
       ['1912.0', 'Hare'],
       ['1913.0', 'Hare'],
       ['1914.0', 'Hare'],
       ['1915.0', 'Lynx'],
       ['1916.0', 'Carrot'],
       ['1917.0', 'Carrot'],
       ['1918.0', 'Carrot'],
       ['1919.0', 'Carrot'],
       ['1920.0', 'Carrot']], dtype='<U32')

# Lecture 4.2

Agenda:
- Coding questions
- Tabs in python. 

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE
- All about final projects

See final project files on github under Course Materials folder

# Lab 4.2

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/IntroSciComp_S2021/blob/main/Class_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
Comparison Operators
<,>,>=,<=,==,!=
Boolean Operators 
and,or,not 
ConditionalStatements 
if,else,elif


**E.3** Exercise 1 on https://www.practicepython.org

In [31]:
name = input("Give me your name: ")
print("Your name is " + name)

Give me your name: Luz
Your name is Luz


In [32]:
age = input("Enter your age: ")
age = int(age)

Enter your age: 23


In [33]:
age = int(input("Enter your age: "))

Enter your age: 23


In [34]:
print("Were" + "wolf")

Werewolf


In [35]:
print("Door" + "man")

Doorman


In [37]:
print(str(4) + "chan")

4chan


In [38]:
print(4 * "chan")

chanchanchanchan


**E.4** Exercise 2 on https://www.practicepython.org

In [39]:
5 % 3

2

In [40]:
6 % 3

0

In [41]:
7 % 3

1

In [44]:
if age > 17: 
    print("can see a rated R movie")
elif age < 17 and age > 12:
    print("can see a rated PG-13 movie")
else: 
    print("can only see rated PG movies")

can see a rated R movie


In [47]:
a = 3
if a == 3:
    print("the variable has the value 3")
elif a != 3:
    print("the variable does not have the value 3")

the variable has the value 3


In [48]:
a = 8
if a == 3:
    print("tha variable has the value 3")
else:
    print("the variable does not have the value 3")

the variable does not have the value 3


Don't forget to do some practicing of what you have been learning, including previous labs

**You did it!**