Name: Luz Ballesteros Gonzalez 

Labpartner(s): Rocio 

In [1]:
# import statements go here
import numpy as np 
import pandas as pd


# Class 5.1

## Monday labs are due Thursday at midnight

Today you all are going to do the lecture! It's Present Your Plots Day.

# Warmups 5.1

### Warmup is short today (20 min) so we have time to focus on your plots.

**W.1** Do Exercise 3 in practice python https://www.practicepython.org

In [3]:
list1 = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
list1

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [8]:
list2 = np.array(list1)
list2

array([ 1,  1,  2,  3,  5,  8, 13, 21, 34, 55, 89])

In [10]:
list3 = list2 < 5
list3 # prints booleans 

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False])

In [11]:
list3 = list2[list2<5]
list3 # prints integers 

array([1, 1, 2, 3])

In [12]:
number = input("Input any number: ")

Input any number: 13


In [13]:
number = int(number)

In [14]:
sol = []

In [15]:
for x in list2:
    if x < number:
        sol.append(x)
print(sol)

[1, 1, 2, 3, 5, 8]


# Lecture 5.1

## Agenda:

- Questions about class or coding
- Review of assignment tokens system
- Show us your plots! Explain your data set, what you did with it, and what your learned, including any difficulties you had and how you solved them.

## Assignment Tokens review

### From syllabus:

Each student will begin the semester with ten assignment tokens, which they can use to miss a lab meeting, an assessment exercise, resubmit an unsatisfactory assignment or turn an assignment in late.

### From: 4.1.1 How to earn more assingment tokens

Studies show students at all levels like gamification. So let’s try this. We are going to institute an assignment token earning system starting next wek. There will be awards for having lots of tokens…and a winner...and prizes. 

Earn assignment tokens for: 
- Doing the data camp chapter before class (1 token)
- Turning in Monday’s lab by Tuesday at midnight (1 token)
- Creating a cool demo or exercise for your classmates (1+ tokens, depending on awesomeness)
- Creating warmup exercises (1+ tokens, depending on how many, quality, etc.)

To earn your tokens, send me and Adrian your proof, code, etc. over slack. That is, in a group message to both Adrian and I.

As always, let me know in your weekly assessments if you have ideas on how to improve this game.



# Lab 5.1

**E.1** Complete intermediate python chapter 4: Loops

Note that loops often are very confusing for new programmers, but they are very powerful and super-useful. You will be seing them again.

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/IntroSciComp_S2021/blob/main/Class_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You might use the resources linked above for supplementary examples. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [16]:
# lists are an ordered way of grouping things (called elements)
# you can construct an empty list x =[]

#you can just add things by using .append()

#list are also iterables and you can loop them 

# Example:
my_list = [1, 3, "Michele", [5, 6, 7]]
for element in my_list:
    print(element)


1
3
Michele
[5, 6, 7]


In [26]:
# Example 2: conditionals follow logical operations and can be used to test equality
grade = input("Enter your grade: ")

if grade >= 90:
    print("A")
    
elif grade >= 80:
    print("B")
    
else:
    print("F") ## not sure why the error happens

Enter your grade: 90


TypeError: '>=' not supported between instances of 'str' and 'int'

**E.3-6** Exercises 4-7 in practice python (see link above)

In [27]:
#Exercise 4 
x = range(2, 11)
x

range(2, 11)

In [28]:
for elem in x:
    print(elem) ## prints out the whole list 

2
3
4
5
6
7
8
9
10


In [33]:
# Exercise 5
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
c = []

In [37]:
for item in a:
    if item in b:
        if item not in c:
            c.append(item)
    
print(c) ## needs the edentation to run with no errors 

[1, 2, 3, 5, 8, 13]


In [40]:
# Exercise 6 
stg = input("Enter a word: ")
stg = str(stg)

Enter a word: lol


In [42]:
rvs = stg[::-1]
rvs

'lol'

In [44]:
if stg == rvs:
    print("Your word is a palindrome")
else:
    print("Your word is NOT a palindrome")
    

Your word is a palindrome


In [45]:
# Exercise 7 
a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [46]:
a1 = []

In [47]:
for number in a:
    if number %2 == 0:
        a1.append(number)
print(a1)

[4, 16, 36, 64, 100]


In [48]:
b1 = [number for number in a if number % 2 == 0]
b1

[4, 16, 36, 64, 100]