Name: Luz Ballesteros Gonzalez 

Labpartner(s) Kara Eckley

In [2]:
# import statements go here
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [3]:
## 1D 
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [4]:
##practice 
a.ndim

1

In [6]:
## practice 
a.shape

(4,)

In [ ]:
## 2-D, 3-D, ... 

In [6]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
b.ndim

2

In [8]:
b.shape

(2, 3)

In [10]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [11]:
c.shape

(2, 2, 1)

In [37]:
len(c)

2

In [12]:
l = np.array([1,10,20,25,35,45,50,60,75,80])
l

array([ 1, 10, 20, 25, 35, 45, 50, 60, 75, 80])

In [15]:
l.shape

(10,)

In [16]:
l.ndim

1

In [19]:
len(l)

10

In [ ]:
## the shape gives the number of rows, and the integers in each row, len gives the lenght 
## so if you have a 1D array with 10 integers then both the len() and the shape will be the same 

In [20]:
## example 1 
example_1 = np.array([[9,7,6,5,4], [10,8,6,4,2]])
example_1

array([[ 9,  7,  6,  5,  4],
       [10,  8,  6,  4,  2]])

In [21]:
#function for array
example_2 = np.arange(10)
example_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
example_3 = np.arange(1,10,2)
example_3

array([1, 3, 5, 7, 9])

In [25]:
example_4 = np.linspace(0,1,5)
example_4

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
example_5 = np.linspace(0,1,5, endpoint=False)
example_5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [29]:
example_6 = np.ones((3,3)) ## 3 rows and 3 col.... how do you get rid of the dots at the end?
example_6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
example_7 = np.zeros((4,4))
example_7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
example_8 = np.eye(4) ## puts ones on diagonal 
example_8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
example_9 = np.diag(np.array([2,4,6])) ## puts the integers in the diagonal 
example_9

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [34]:
example_10 = np.random.rand(3)
example_10

array([0.78202902, 0.9297263 , 0.43848547])

In [36]:
example_11 = np.random.randn(3) ## the last end makes it include the negative
example_11

array([ 0.83209009, -0.33807246,  0.72485112])

In [39]:
example_12 = np.empty([3,3])
example_12
## np.empty creates an array with place holders to then put your data in

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Agenda:

- Programming questions
- Dr. Coupe will show some plots 
- Examples of for loops

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [40]:
# set random integers/arrays 
np.random
# set random seed
np.random.seed(1250)
# if you use randit it gives you integers within a range 
np.random.randint(1,5)


In [44]:
## you can set limits  
a = [5] # this will be the starting value 

for x in range(20):
    y = np.random.randint(1,4)
    z = a[-1]
    if y == 2: 
        z = min(5, y - 1)
    else: 
        z = z + 1
    a.append(z)

print(a)

[5, 6, 1, 1, 2, 3, 4, 5, 6, 7, 1, 2, 1, 2, 1, 1, 2, 3, 1, 2, 3]


### Congratulations! ¡Felicidades! You finished Intermediate Python!