Name Kathrene Lo

Labpartner(s) Adam Sanjar

In [1]:
# import statements go here
#Josh Coupe from Rutgers. My Zoom finally got updated because Josh's Zoom session required an updated version. 

# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

Manual construction of arrays
Exercise 1:

In [ ]:
import numpy as np
#1-D:
a= np.array([0, 1, 2, 3])
a

In [4]:
a.ndim

1

In [5]:
a.shape

(4,)

In [6]:
len(a)

4

In [7]:
#2-D:
b= np.array([[0, 1, 2], [3, 4, 5]])  #2x3 arrary
b

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
len(b)

2

In [12]:
#3-D:
c= np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [13]:
c.shape

(2, 2, 1)

In [14]:
k= np.array([[11, 25, 94], [48, 60, 26]])
k

array([[11, 25, 94],
       [48, 60, 26]])

In [15]:
len(k)

2

In [17]:
np.shape(k)

(2, 3)

In [18]:
#len() gives the first number or amount of rows expressed in np.shape()
k.ndim

2

In [19]:
#I think ndim gives the amounts of sets in the array. Let me test this hypothesis.
len(c)

2

In [20]:
c.ndim

3

In [24]:
#looks like that's not the case
?ndim
#it doesn't work !!!! Research

Object `ndim` not found.


In [ ]:
#ndim is the dimension of the shape. So it would be amount of numbers the shape produces.

Functions for creating arrays
Exercise 2:

In [2]:
import numpy as np
z= np.arange(16)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
y= np.arange(4, 17, 4)
y

array([ 4,  8, 12, 16])

In [7]:
x= np.linspace(1, 6, 10)
x

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [9]:
w= np.linspace(1, 6, 10, endpoint = False)
w

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [10]:
v= np.ones((4,2))
v

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
u= np.zeros((4,3))
u

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
t= np.eye(5)
t

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
s= np.diag(np.array([4,6,8,13]))
s

array([[ 4,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0,  8,  0],
       [ 0,  0,  0, 13]])

In [14]:
r= np.random.rand(4)
r

array([0.10322932, 0.62152265, 0.46939328, 0.64077973])

In [15]:
q= np.random.rand(7)
q

array([0.02451311, 0.57420037, 0.0199519 , 0.17031162, 0.57404545,
       0.29378882, 0.26979751])

In [16]:
np.random.seed(3456)
#not sure how the numbers work

In [17]:
p= np.random.rand(4)
p

array([0.64317051, 0.46296798, 0.0626953 , 0.87496673])

In [18]:
o= np.random.rand(4)
o

array([0.97749171, 0.82488721, 0.11339586, 0.3087274 ])

In [22]:
np.random.seed(5)

In [24]:
n= np.random.rand(4)
n

array([0.48841119, 0.61174386, 0.76590786, 0.51841799])

In [25]:
np.random.seed(356901)
n

array([0.48841119, 0.61174386, 0.76590786, 0.51841799])

In [26]:
np.random.seed(0)
n

array([0.48841119, 0.61174386, 0.76590786, 0.51841799])

In [30]:
np.empty?
#Docstring:
#empty(shape, dtype=float, order='C')
#Return a new array of given shape and type, without initializing entries.
np.empty(3)

array([1.43291126e-311, 0.00000000e+000, 9.89803212e+164])

In [31]:
np.empty(3, order= 'F')

array([1.43291126e-311, 0.00000000e+000, 9.89803212e+164])

In [33]:
np.empty(3, dtype=float, order='C')

array([1.43291126e-311, 0.00000000e+000, 9.89803212e+164])

In [34]:
np.empty(3, dtype=int, order='F')
#What does it do? When might it be useful?

array([0, 0, 0])

# Lecture 5.2

### Agenda:

- Programming questions
- Dr. Coupe will show some plots 
- Examples of for loops

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

$\alpha^2$

In [21]:
#alpha^2 = \alpha^2 in Markdown

In [ ]:
#Facemap to cartopy
#runoff from South America
#$\pi$ = gives pi sign in the graph
#what does the % mean? What does ! do/mean? What does is a tuple and iteration?
#mounting service to desktop; started with Pascal, then Java before starting with Python in 2015

In [ ]:
#decimals are floats and cannot be used as integers unless maybe converted
#tuple

### Congratulations! ¡Felicidades! You finished Intermediate Python!

In [ ]:
#Woohoo! Not really because I have to catch up on all the assignments. But I'll be momentarily excite/relieved once caught up!