    Name Sandip Regmi

Labpartner(s): Lilly Elliot and August Luna

In [5]:
#import statements go here
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Lab 4.2 

Wednesday labs are due Sunday at midnight

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner in your breakout room, they are your partner for this lab. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Blackboard.

# Warmups 4.2

W.1-3 Do exercises 1-3 in http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 4.1  on how to load in the data file

In [7]:
data_pd = pd.read_csv('http://scipy-lectures.org/_downloads/populations.txt')

In [16]:
#Exercise 1
array1 = np.arange(1,16).reshape(3,5).T
array1

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [21]:
#Exercise2
array2 = array1[1,:]
array2

array([ 2,  7, 12])

In [22]:
array3 = array1[3,:]
array3

array([ 4,  9, 14])

In [1]:
#Above were done with misunderstanding on class. 

In [6]:
text1 = pd.read_csv('populations.txt','\t',index_col=0)
text1

hare     lynx  carrot
# year                          
1900    30000.0   4000.0   48300
1901    47200.0   6100.0   48200
1902    70200.0   9800.0   41500
1903    77400.0  35200.0   38200
1904    36300.0  59400.0   40600
1905    20600.0  41700.0   39800
1906    18100.0  19000.0   38600
1907    21400.0  13000.0   42300
1908    22000.0   8300.0   44500
1909    25400.0   9100.0   42100
1910    27100.0   7400.0   46000
1911    40300.0   8000.0   46800
1912    57000.0  12300.0   43800
1913    76600.0  19500.0   40900
1914    52300.0  45700.0   39400
1915    19500.0  51100.0   39000
1916    11200.0  29700.0   36700
1917     7600.0  15800.0   41800
1918    14600.0   9700.0   43300
1919    16200.0  10100.0   41300
1920    24700.0   8600.0   47300

In [7]:
#For mean and standard deviation calculation:
print(text1.min())

hare       7600.0
lynx       4000.0
carrot    36700.0
dtype: float64


In [8]:
print(text1.std())

hare      21413.981859
lynx      16655.999920
carrot     3404.555771
dtype: float64


In [10]:
text1.idxmax()

hare      1903
lynx      1904
carrot    1900
dtype: int64

In [13]:
#for transpose of the matrix
text_trans = text1.transpose()
print(text_trans)
print(text_trans.idxmax())

# year     1900     1901     1902     1903     1904     1905     1906  \
hare    30000.0  47200.0  70200.0  77400.0  36300.0  20600.0  18100.0   
lynx     4000.0   6100.0   9800.0  35200.0  59400.0  41700.0  19000.0   
carrot  48300.0  48200.0  41500.0  38200.0  40600.0  39800.0  38600.0   

# year     1907     1908     1909  ...     1911     1912     1913     1914  \
hare    21400.0  22000.0  25400.0  ...  40300.0  57000.0  76600.0  52300.0   
lynx    13000.0   8300.0   9100.0  ...   8000.0  12300.0  19500.0  45700.0   
carrot  42300.0  44500.0  42100.0  ...  46800.0  43800.0  40900.0  39400.0   

# year     1915     1916     1917     1918     1919     1920  
hare    19500.0  11200.0   7600.0  14600.0  16200.0  24700.0  
lynx    51100.0  29700.0  15800.0   9700.0  10100.0   8600.0  
carrot  39000.0  36700.0  41800.0  43300.0  41300.0  47300.0  

[3 rows x 21 columns]
# year
1900    carrot
1901    carrot
1902      hare
1903      hare
1904      lynx
1905      lynx
1906    carrot
1907   

# Lecture 4.2

Agenda:
- Coding questions
- Tabs in python. 

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE
- All about final projects

See final project files on github under Course Materials folder

# Lab 4.2

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/IntroSciComp_S2021/blob/main/Class_materials/resources.md

In [ ]:
#DECISION MAKING STATEMENT\

#IF statement helps on execution of two or more conditional statement.

#the true result prints function where as the false condition goes to check if there is any conditions on ELSE statement. These are powerful statement if combined with ELSE IF.

# to check the year is leap or not - i will try. 



**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
#Leap Year PSEUDO CODE
# year divisible by 4 , 100 and 400

In [1]:
def leap(year):
    if year % 400 == 0:
        return True
    
    if year % 100 == 0:
        return False
    
    if year % 4 == 0:
        return True
    
    else:
        
        return False


In [2]:
print(leap(2020))


True


In [3]:
print(leap(2014))

False


**E.3** Exercise 1 on https://www.practicepython.org

In [ ]:
home = input('Hey, Whats your hometown name?')
home = str(home)
print('There it go by name '+  str(home))

**E.4** Exercise 2 on https://www.practicepython.org

In [ ]:
check = input("Enter a number: ")
a1 = int(check) % 2
if e4 == 0:
    print(str(check)+" is an even number")
else:
    print(str(check)+" is an odd number")

Don't forget to do some practicing of what you have been learning, including previous labs

**You did it!**