Name

Labpartner(s)

In [4]:
# import statements go here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Exercise: Simple arrays
# Create a simple two dimensional array. First, redo the examples from above. And then create your own: how about odd numbers counting backwards on the first row, and even numbers on the second?
# Use the functions len(), numpy.shape() on these arrays. How do they relate to each other? And to the ndim attribute of the arrays?

# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [12]:
# 1D Arrays
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [10]:
a.ndim


1

In [11]:
a.shape

(4,)

In [13]:
# 2D arrays
b = np.array([[0, 1, 2], [3, 4, 5]])
b
             

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [17]:
len(b)

2

In [18]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [19]:
c.shape

(2, 2, 1)

In [20]:
array_1 = np.arange(1, 11+2, 2)
np.flip(array_1)

array([11,  9,  7,  5,  3,  1])

In [37]:
array_2 = np.arange(0, 10+2, 2)
array_2

array([ 0,  2,  4,  6,  8, 10])

In [38]:
array_3 = np.array([[array_1],[array_2]])
array_3

array([[[ 1,  3,  5,  7,  9, 11]],

       [[ 0,  2,  4,  6,  8, 10]]])

In [39]:
array_3.shape

(2, 1, 6)

In [40]:
len(array_3)

2

In [41]:
array_3.ndim

3

In [42]:
# Array_3 is a three dimensional array.

In [ ]:
# Functions for creating arrays
# evenly spaced

In [47]:
d = np.arange(10) # 0 .. n-1  (!)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# (start, end (exclusive), step)
e = np.arange(1, 9, 2)
e

array([1, 3, 5, 7])

In [ ]:
# by number points 
# (start, end, num-points)

In [50]:
f = np.linspace(0, 1, 6)
f

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [52]:
g = np.linspace(0, 1, 5, endpoint=False) #to get rid of 10
g

array([0. , 0.2, 0.4, 0.6, 0.8])

In [ ]:
# Common arrays
# reminder: (3, 3) is a tuple

In [53]:
h = np.ones((3, 3))
h

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
i = np.zeros((2,2))
i

array([[0., 0.],
       [0., 0.]])

In [56]:
j = np.eye(3) #first, mid, and last numb is same
j

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
# this func places number diagonal
k = np.diag(np.array([1, 2, 3, 4])) 
k

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#np.random: random numbers

In [58]:
l = np.random.rand(4)
l

array([0.90601028, 0.7669453 , 0.44880015, 0.67981552])

In [59]:
m = np.random.randn(4)
m

array([ 0.47831796, -0.58594047,  0.2364637 , -0.89631742])

In [61]:
np.random.seed(1234)

In [ ]:
#Exercise: Creating arrays using functions

# Experiment with arange, linspace, ones, zeros, eye and diag.
# Create different kinds of arrays with random numbers.
# Try setting the seed before creating an array with random values.
# Look at the function np.empty. What does it do? When might this be useful?

In [62]:
q = np.arange(20)
q

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
# (start, end, num-points)
r = np.linspace(0, 1, 5)
r

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [66]:
s = np.linspace(0, 1, 5, endpoint=False)
s

array([0. , 0.2, 0.4, 0.6, 0.8])

In [67]:
t = np.ones((5, 5))
t

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
u = np.eye(5) #first and last numb is same
u

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
v = np.diag(np.array([1, 2, 3, 4, 5])) 
v

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [73]:
w = np.random.rand(10)
w

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [74]:
x = np.random.randn(10)
x

array([ 1.56963721e-02, -2.24268495e+00,  1.15003572e+00,  9.91946022e-01,
        9.53324128e-01, -2.02125482e+00, -3.34077366e-01,  2.11836468e-03,
        4.05453412e-01,  2.89091941e-01])

In [85]:
#np empty returns a new array of given shape and type, without initializing entries.
np.empty([2,2])


array([[0.2, 0.4],
       [0.6, 0.8]])

In [87]:
import random

random.seed(10)
print(random.random())

random.seed(15)
print(random.random())

0.5714025946899135
0.965242141552123


# Lecture 5.2

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
# len() returns the size of the first dimension
# The seed() method is used to initialize the random number generator.
# The random number generator needs a number to start with (a seed value), to be able to generate a random number.

### Congratulations! ¡Felicidades! You finished Intermediate Python!