Name: 

Lab partner:

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner in your breakout room, they are your partner for this lab. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Blackboard.

# Lecture 2.1

Lecture Agenda:
* more review of indexing (before warmups)
* go over syllabus, grading
* introduction of assessment exercise
* questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [1]:
title = "Monty Python"

In [9]:
# How do I print out "Monty" and "Python"?




In [8]:
# You don't have to specify the beginning or the end index




In [7]:
# How do I print them out using negative indices?




# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [122]:
list1=[1,2,3,4,5,6,7,8,9,10]

**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [19]:
print(list1[0])

1


In [124]:
list1[9]

10

**W.3** Print the second element through the ninth element of list1

In [20]:
print(list1[1:])


[2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.4** Print the sum of the first and last elements of list1

In [21]:
print(list1[0]+list1[9])

11


**W.5** Print the product of the second and third element of list1

In [22]:
print(list1[1],list1[2])

2 3


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [23]:
list2=[list1[1],list1[3],list1[5],list1[7],list1[9]];print(list2)

[2, 4, 6, 8, 10]


In [24]:
#We need to open braket to create new list

**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [25]:
print(list1[4]+list2[4])

15


**W.8** Print the product of the second element of list1 and the second element of list2.

In [26]:
print(list1[1]+list2[1])

6


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [27]:
list1[0]=5;print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [28]:
list2[-1]=5;print(list2[-1])

5


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [47]:
list3=list1+list2

**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [30]:
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


In [31]:
list4=[list3]+['Edoardo','Davila']

In [32]:
print(list4)

[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5], 'Edoardo', 'Davila']


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [51]:
whos

Variable   Type    Data/Info
----------------------------
list1      list    n=10
list2      list    n=5
list3      list    n=15
list4      list    n=2
name       list    n=1


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

In [2]:
whos

Interactive namespace is empty.


**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

In [4]:
#it is a piece of reusable code that helps to solve a particular task, for example, type()

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

In [6]:
help(print) #the output explains how to use the function and what it does when applied

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



**E.4** What is a method? How is it different from a function? Demonstrate

In [7]:
#It is a function that works with specific funcionts

In [8]:
room=['bedroom','bathroom','living room']

In [11]:
room.index('bathroom')

1

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [33]:
sorted(list3, key=None)

[2, 2, 3, 4, 4, 5, 5, 5, 6, 6, 7, 8, 8, 9, 10]

**E.6** Repeat W.12 using a method

In [49]:
list3.append(11)

In [50]:
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 11]


**E.7** What is a python package?

In [54]:
#It is a directory of python scripts. Each script works with specific functions, methods, and types

In the anaconda .distribution you all have, most of the packages you will need are already installed. Later on, we will go over how to add more packages

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

In [56]:
#You need to import it. For example,

In [57]:
import math

In [59]:
C=(2*math.pi)

In [60]:
print(C)

6.283185307179586


**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [115]:
import numpy

In [118]:
array1=numpy.array([1,2,3,4,5,6,7,8,9,10])

**E.10** Repeat W.2-W.6 using arrays

In [125]:
array1[0]

1

In [126]:
array1[9]

10

In [127]:
array1[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [128]:
array1[0]+[9]

array([10])

In [132]:
array1[2:4]

array([3, 4])

In [136]:
array2=[array1[1],array1[3],array1[5],array1[7],array1[9]]

In [137]:
print(array2)

[2, 4, 6, 8, 10]
