Name

Labpartner(s)

In [ ]:
# import statements go here


# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [21]:
import numpy as np

In [22]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [23]:
a.ndim

1

In [24]:
a.shape

(4,)

In [25]:
len(a)

4

In [31]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
b.ndim

2

In [33]:
b.shape

(2, 3)

In [34]:
len(b)

2

In [35]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [36]:
c.shape

(2, 2, 1)

In [26]:
array1=np.arange(1,11+2,2)
np.flip(array1)

array([11,  9,  7,  5,  3,  1])

In [27]:
array2=np.arange(0,10+2,2)
array2

array([ 0,  2,  4,  6,  8, 10])

In [28]:
array3=np.array([[array1],[array2]])
array3

array([[[ 1,  3,  5,  7,  9, 11]],

       [[ 0,  2,  4,  6,  8, 10]]])

In [29]:
print(array3.shape)

(2, 1, 6)


In [37]:
array3.ndim

3

In [30]:
len(array3)

2

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(0,20+2,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [45]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [46]:
np.linspace(0,5,5, endpoint=False)

array([0., 1., 2., 3., 4.])

In [47]:
np.ones((1,1))

array([[1.]])

In [49]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [51]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
np.diag(np.array([1, 2, 4, 8]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 8]])

In [65]:
np.random.rand(5) 

array([0.80187218, 0.95813935, 0.87593263, 0.35781727, 0.50099513])

In [64]:
np.random.randn(5)

array([-1.0336313 ,  2.02683258,  0.66250904,  0.67524634, -0.94029827])

In [66]:
np.random.seed(6789)
np.random.rand()

0.9841611626286128

In [69]:
np.empty([3,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [71]:
np.empty([4,2], dtype=int)

array([[4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408]])

# Lecture 5.2

### Agenda:

- Programming questions
- Dr. Coupe will show some plots 
- Examples of for loops

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
import numpy as np
np.random.rand() #random number generator

np.random.seed(123) #starting from a seed
np.random.rand()

#Coin toss
np.random.seed(123)
coin=np.random.randint(0,2) #randomly generate 0 or 1
print(coin)
if coin == 0:
    print('heads')
else:
    print('tails')

#dice
dice=np.random.randint(1, 7)

if dice <= 2:
    step= step-1
elif dice<6 :
    step= step +1
else:
    step= step + np.random.randint(1, 7)

print(dice); print(step)

#Heads or Tails
np.random.seed(123)
outcomes= []
for x in range(10):
    coin=np.random.randint(0,2)
    if coin== 0:
        outcomes.append('heads')
    else:
        outcomes.append('tails')
print(outcomes)

PRACTICE

In [4]:
import numpy as np

In [5]:
a=np.random.randint(20)
a

2

In [6]:
b=np.array([np.random.rand(20)])
b

array([[0.22685145, 0.55131477, 0.71946897, 0.42310646, 0.9807642 ,
        0.68482974, 0.4809319 , 0.39211752, 0.34317802, 0.72904971,
        0.43857224, 0.0596779 , 0.39804426, 0.73799541, 0.18249173,
        0.17545176, 0.53155137, 0.53182759, 0.63440096, 0.84943179]])

In [7]:
b[b>0.5]

array([0.55131477, 0.71946897, 0.9807642 , 0.68482974, 0.72904971,
       0.73799541, 0.53155137, 0.53182759, 0.63440096, 0.84943179])

In [10]:
c=np.linspace(0,25,25)
d=[]


In [11]:
for element in c:
    if element > 15:
        d.append(element+10)

In [12]:
d

[25.625,
 26.666666666666668,
 27.708333333333336,
 28.75,
 29.791666666666668,
 30.833333333333336,
 31.875,
 32.91666666666667,
 33.958333333333336,
 35.0]

### Congratulations! ¡Felicidades! You finished Intermediate Python!