Name: Rocio Hernandez

Lab partner:

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner in your breakout room, they are your partner for this lab. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Blackboard.

# Lecture 2.1

Lecture Agenda:
* more review of indexing (before warmups)
* go over syllabus, grading
* introduction of assessment exercise
* questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [21]:
title = "Monty Python"

In [22]:
title[0:5]

'Monty'

In [23]:
title[6:12]

'Python'

In [24]:
title[0:]

'Monty Python'

In [20]:
# How do I print out "Monty" and "Python"?






NameError: name 'title' is not defined

In [25]:
print(title)

Monty Python


In [8]:
# You don't have to specify the beginning or the end index

In [7]:
# How do I print them out using negative indices?

# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [57]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [58]:
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [21]:
print(list1[0])

1


In [22]:
print(list1[-1])

10


**W.3** Print the second element through the ninth element of list1

In [23]:
print(list1[1:9])

[2, 3, 4, 5, 6, 7, 8, 9]


**W.4** Print the sum of the first and last elements of list1

In [24]:
print(list1[0] + list1[9])

11


**W.5** Print the product of the second and third element of list1

In [25]:
(list1[1] * list1[2])

6

**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [26]:
list2 = (list1[1], list1[3], list1[5], list[7], list[9])

TypeError: 'type' object is not subscriptable

In [27]:
print(list2)

[2, 4, 6, 8, 5, 55, 55]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [28]:
print(list1[4] + list2[-1])

60


**W.8** Print the product of the second element of list1 and the second element of list2.

In [29]:
(list1)[1] * (list2)[1]

8

**W.9** Replace the first element of list1 with the integer 5. Print the list

In [30]:
list1[0] = 5

In [31]:
print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [32]:
list2 = [2, 4, 6, 8, 10]

In [33]:
list2[4] = 5

In [34]:
print(list2)

[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [35]:
list3 = (list1[0:] + list2[0:])

In [36]:
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [42]:
list4 = [list3, "Rocio Hernandez"]

In [43]:
print(list4)

[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5], 'Rocio Hernandez']


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [60]:
who

list	 list1	 list2	 list3	 list5	 lista	 title	 


In [61]:
whos

Variable   Type    Data/Info
----------------------------
list       list    n=10
list1      list    n=10
list2      list    n=5
list3      list    n=15
list5      str     Rocio Hernandez
lista      str     Rocio Hernandez
title      str     Monty Python


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

In [ ]:
# You're essentially starting a python lesson again, however all of your code remaines saved. 

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

In [ ]:
# A function is like the equation that help you reflect what you want to communicate in code. It is a system that allows you to code strategically. 

In [64]:
round(1.75, 1)

1.8

In [ ]:
# or I can also just insert one number and python can conclude that I want it round up to the nearest whole number. 

In [65]:
round(1.2987387549879437)

1

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

In [66]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [ ]:
# You would write help and then choose "the what you need help in" and insert it into the paranthesis. Python will then give you an explanation.

In [67]:
help(int)

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 

**E.4** What is a method? How is it different from a function? Demonstrate

In [ ]:
# A method is something specific to the object that you are utilizing for your code- a way of doing an action only capable for a list, or a string, etc. So, if I was using a string function, I could use the replacing methods to help me code more effectively. It is somewhat of a subfunction.  

In [4]:
#Example 

In [11]:
a = ["John", "Sam", "Rocky", "Rory"]

In [12]:
print(a)

['John', 'Sam', 'Rocky', 'Rory']


In [16]:
a.append("Tom")

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [69]:
max(list1)

10

**E.6** Repeat W.12 using a method

In [17]:
#Create a list named list4 which contains list3 + a list of strings containing your full name.

In [39]:
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


In [44]:
print(list4)

[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5], 'Rocio Hernandez']


In [52]:
list3.append(16)

In [55]:
list4.index("Rocio Hernandez")

1

**E.7** What is a python package?

In [ ]:
# A package was explained as a directory, a set of functions and methods assigned to the style of coding you are working towards.

In the anaconda .distribution you all have, most of the packages you will need are already installed. Later on, we will go over how to add more packages

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

In [ ]:
#You would need to add code to your script in order to give python the order of utilizing that installed package. 

In [ ]:
#Example: you would first write the package name.

In [56]:
import numpy

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [59]:
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [60]:
import numpy

In [61]:
numpy.array

<function numpy.array>

In [63]:
numpy.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**E.10** Repeat W.2-W.6 using arrays

In [65]:
# Print the first element of list1. Then print the last element of list1 on the next line.

In [66]:
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [67]:
numpy.array(list1[0])

array(1)

In [68]:
numpy.array(list1[-1])

array(10)

In [69]:
# Print the second element through the ninth element of list1

In [72]:
numpy.array(list1[1:9])

array([2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
#Print the sum of the first and last elements of list1

In [80]:
numpy.array(list1[0] + list1[9])

array(11)

In [ ]:
#Print the product of the second and third element of list1

In [82]:
numpy.array(list1[1] * list1[2])

array(6)

In [83]:
#Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [84]:
numpy.array(list2)

array([2, 4, 6, 8, 5])