Name: Rocio Hernandez

Labpartner(s) Dwight Capus

In [6]:
# import statements go here
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [ ]:
#Manual construction of arrays

In [8]:
np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

In [9]:
a = np.array([0, 1, 2, 3])
>>> a
array([0, 1, 2, 3])
>>> a.ndim
1
>>> a.shape
(4,)
>>> len(a)
4

NameError: name 'array' is not defined

In [5]:
a = np.array([0, 1, 2, 3])
>>> a
array([0, 1, 2, 3])
>>> a.ndim
1
>>> a.shape
(4,)
>>> len(a)
4
2-D, 3-D,:
>>>
>>> b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
>>> b
array([[0, 1, 2],
       [3, 4, 5]])
>>> b.ndim
2
>>> b.shape
(2, 3)
>>> len(b)     # returns the size of the first dimension
2

>>> c = np.array([[[1], [2]], [[3], [4]]])
>>> c
array([[[1],
        [2]],

       [[3],
        [4]]])
>>> c.shape
(2, 2, 1)

SyntaxError: invalid syntax (<ipython-input-5-a3f9915c01e0>, line 10)

# Lecture 5.2

### Agenda:

- Programming questions
- Dr. Coupe will show some plots 
- Examples of for loops

#T

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

### Congratulations! ¡Felicidades! You finished Intermediate Python!

In [ ]:
#This reminds me of the Fatality final round on Mortal Combat when they say, "Finish her!"
#I do believe Data camp finished me vs the other way around. 
# I have so much to learn. 
