Name: August

Labpartner(s): Christopher

In [1]:
# import statements go here
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [20]:
#Create a simple two dimensional array. First, redo the examples from above. 
#And then create your own: how about odd numbers counting backwards on the first row, 
#and even numbers on the second?b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array

b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array

my_array= np.zeros((2,2))


In [21]:
print(my_array)


[[0. 0.]
 [0. 0.]]


In [ ]:
#Use the functions len(), numpy.shape() on these arrays. 
#How do they relate to each other? And to the ndim attribute of the arrays?

In [25]:
len(b)
len(my_array)
#len(shows the amount of items in a list, not what the items contain 
#(describes how many boxes, not what's inside the box))

2

In [11]:
#Experiment with arange, linspace, ones, zeros, eye and diag.
np.arange(4,5+0.1, 0.1)

np.arange(6,4-1, -1)

In [30]:
np.linspace(1,10, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [32]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.zeros((4,11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.eye(4) #creates this inconsistent system I like it.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.diag(np.array([1,2,3,4])) #makes an array diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [42]:
#Create different kinds of arrays with random numbers

np.array(np.random.randint(1,5,10))

array([3, 3, 4, 3, 4, 1, 4, 2, 3, 3])

In [46]:
rando= np.array(np.random.randint(1,5,10))

zeros= np.zeros((2,5))

zeros[zeros==0]= rando

In [47]:
zeros

array([[4., 1., 4., 1., 3.],
       [2., 4., 1., 3., 3.]])

In [51]:
np.random.randn(5)

array([ 0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [61]:
np.random.seed(1234) #NumPy random seed is simply a function that sets the random seed of the NumPy pseudo-random number generator.

In [62]:
np.random.randint(3)

2

In [65]:
np.empty((5,5))
#Return a new array of given shape and type, without initializing entries.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Lecture 5.2

### Agenda:

- Programming questions
- Dr. Coupe will show some plots 
- Examples of for loops

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:

all_walks = []  # this is the list i put my data in once I make it. Right now it's empty
for i in range(500) : #this is how many times I want the system to go for
    random_walk = [0] #this is where I start
    for x in range(100) : #this is how many dice rolls i am going for.
        step = random_walk[-1]
        dice = np.random.randint(1,7) #how many sides my dice have
        if dice <= 2:
            step = max(0, step - 1)  #max is so I don't get any negatives
        elif dice <= 5:
            step = step + 1
        else:
            step = step + np.random.randint(1,7)
        if np.random.rand() <= 0.001 :
            step = 0
        random_walk.append(step)
    all_walks.append(random_walk)

# Create and plot np_aw_t
np_aw_t = np.transpose(np.array(all_walks)) #changes shape of the system

# Select last row from np_aw_t: ends
ends = np_aw_t[-1,:]

# Plot histogram of ends, display plot
plt.hist(ends)
plt.show()

### Congratulations! ¡Felicidades! You finished Intermediate Python!