Name: Christopher De La Rosa

Labpartner(s)

In [2]:
# import statements go here

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Class 5.2

Dr. Harrison is attending remotely and presenting at the AAAS annual conference "Understanding Dynamic Ecosystems" in the session ""Biosphere Responses to Geoengineering" https://meetings.aaas.org

Postdoc Josh Coupe, a seasoned scientific programmer, will be hosting class

# Warmups 5.2

**W.1** Go through 1.4.1.2 Creating Arrays in the scipy lecture notes, including the exercises. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [3]:
a = np.array([0, 1, 2, 3])

In [4]:
a

array([0, 1, 2, 3])

In [5]:
a.ndim

1

In [6]:
a.shape

(4,)

In [7]:
len(a)

4

In [8]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array

In [9]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
len(b)

2

In [13]:
c = np.array([[[1], [2]], [[3], [4]]])

In [14]:
c.shape

(2, 2, 1)

In [15]:
c.ndim

3

In [26]:
d = np.array([[5,3,1], [6,4,2]])

In [27]:
len(d)

2

In [28]:
d.shape

(2, 3)

In [29]:
d.ndim

2

In [30]:
aa = np.arange(10) # 0 .. n-1  (!)

In [31]:
bb = np.arange(1, 9, 2) # start, end (exclusive), step

In [33]:
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
bb

array([1, 3, 5, 7])

In [35]:
cc = np.linspace(0, 1, 6)   # start, end, num-points

In [36]:
cc

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [37]:
dd = np.linspace(0, 1, 5, endpoint=False)

In [38]:
dd

array([0. , 0.2, 0.4, 0.6, 0.8])

In [39]:
aaa = np.ones((3, 3))  # reminder: (3, 3) is a tuple

In [40]:
aaa

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
bbb = np.zeros((2, 2))

In [42]:
bbb

array([[0., 0.],
       [0., 0.]])

In [43]:
ccc = np.eye(3)

In [44]:
ccc

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
ddd = np.diag(np.array([1, 2, 3, 4]))

In [46]:
ddd

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [47]:
aaaa = np.random.rand(4)       # uniform in [0, 1]

In [48]:
aaaa

array([0.51478407, 0.48422132, 0.40013812, 0.50461573])

In [49]:
bbbb = np.random.randn(4)      # Gaussian


In [50]:
bbbb

array([-0.19071613, -0.44929372,  0.4113639 ,  1.69931602])

In [51]:
np.random.seed(1234)        # Setting the random seed

In [52]:
np.empty

<function numpy.empty>

# Lecture 5.2

### Agenda:

- Programming questions
- Dr. Coupe will show some plots 
- Examples of for loops

# Lab 5.2

**E.1** Complete Lab 5.1 if you haven't allready


**E.2** Complete intermediate python chapter 5: Case study on hacker statistics


**E.3** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
#imma be honest it took me a minute to understand the concept but it is quite useful

#to set seed import numpy and then np.random.seed(###)
#np.random.randint(can help set random parameters, ex. 1, 7 for 6 sided die)

### Congratulations! ¡Felicidades! You finished Intermediate Python!