Name

Labpartner(s)

In [2]:
#import statements go here

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Class 7.1

Hope everyone is recovering from the freeze. Being in survival mode is stressful! I am going to attemt to be easy on you this week. As announced, there are no labs assigned last week, we are just taking a pass on those. I may have to shuffle some of the later material in the schedule, TBD.

I am having special office hours tomorrow, Tuesday 2-3 on the class zoom channel. I am asking those of you who are behind on any labs to check in with me and make a plan. If you can't make that time, let's schedule another one ASAP. Please note that you cannot miss these early labs and pass the class, and the material builds, so it is critical we get you caught up.


This week we are going to do more plotting, learn about functions, and apply this to your datasets. Next Monday we will have present your work day again, see below for details. Hopefully at this point the material is building to the point where it is not all forein and you will feel a bit more confident.

Originally we had introduction of Zotero and a CV assignment on the schedule for this week, but I'm pushing that until next week so we have less new material to deal with this week.

# Warmups 7.1

**W.1** Go through 1.4.1.5 Indexing and Slicking in the scipy lecture notes, up to the exercises, which you will do on Wednesday. http://scipy-lectures.org/intro/numpy/array_object.html#id2

In [4]:
a = np.arange(10)

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[0], a[2], a[-1]

(0, 2, 9)

In [7]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
aa = np.diag(np.arange(3))

In [9]:
aa[1,1]

1

In [10]:
aa[2,1] = 10

In [11]:
aa

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [12]:
a[1]

1

In [13]:
aaa = np.arange(10)

In [14]:
aaa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
aaa[2:9:3] # [start:end:step]

array([2, 5, 8])

In [16]:
aaa[:4]

array([0, 1, 2, 3])

In [17]:
aaa[1:3]

array([1, 2])

In [18]:
aaa[::2]

array([0, 2, 4, 6, 8])

In [19]:
aaa[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
aaaa = np.arange(10)

In [21]:
aaaa[5:] = 10

In [22]:
aaaa

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [23]:
b = np.arange(5)

In [24]:
aaaa[5:] = b[::-1]

In [25]:
aaaa

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# Lecture 7.1

### Agenda:

- The Parable Of Finding Nemo, or How To Do The Seemingly Impossible
- Questions
- Functions!


### Questions

### Functions

Functions are super-useful for doing repetative tasks. You have been using pre-defined functions constantly, when you define arrays, make a plot, or analyse data. Now you are going to learn to write your own.

For more information on functions and documenting:
- http://scipy-lectures.org/intro/language/functions.html?highlight=functions
- https://realpython.com/documenting-python-code/


Basic syntax:

In [26]:
# first you define the function

def function_name():
    # some code that does something
    print('Inside the function')

In [27]:
# then you call the function
function_name()

Inside the function


Note that defined funtions show up using whos

In [28]:
whos

Variable        Type        Data/Info
-------------------------------------
a               ndarray     10: 10 elems, type `int32`, 40 bytes
aa              ndarray     3x3: 9 elems, type `int32`, 36 bytes
aaa             ndarray     10: 10 elems, type `int32`, 40 bytes
aaaa            ndarray     10: 10 elems, type `int32`, 40 bytes
b               ndarray     5: 5 elems, type `int32`, 20 bytes
function_name   function    <function function_name at 0x00000245B0F39940>
np              module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
pd              module      <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
plt             module      <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>


That's a really useless function, let's make a better one.

In [29]:
# usually you want to pass a varible of some sort to the function to manipulate

def circle_area(radius):
    area = 3.14*radius**2
    return area   # the return statement means that the function will return that variable

In [30]:
circle_area(5)

78.5

What happens if I don't add the required input?

What happens if I omit the return statement?

How do I save the function output to a variable?

Does the area variable inside the function exist outside of it?

Note I also could have made my function like this:

In [31]:
def circle_area4(radius):
    return 3.14*radius**2

In [32]:
circle_area4(5)

78.5

### Parsing for bad imput

Note my above function will work even if the input is negative, which is not reasonable. So I probably want to include a statement that checks if the input is weird.

In [33]:
def circle_area5(radius):
    
    # put in an if statement to handle bad inputs
    
    
    return 3.14*radius**2

In [34]:
circle_area5(-3)

28.26

In [35]:
circle_area5(3)

28.26

### Using packages within functions

We can also have import statements within a function, but this can slow the function down if the package is not loaded already

In [ ]:
def circle_area6(radius):
    import numpy as np
    
    return np.pi*radius**2

In [ ]:
circle_area6(3) # note this is a much more accurate

We can have the function inputs have pre-defined default values, so that if you don't pass a variable it will use the default

In [ ]:
def circle_area7(radius = 3):
    import numpy as np #import numpy so we can use the more exact value of pi
    
    return np.pi*radius**2

In [ ]:
circle_area7() # no argument given, so uses radius = 3 by default

Is numpy imported outside the function? Let's check

In [ ]:
# can our function handle lists? Let's check
r = [1,2,3]
circle_area7(r)



In [ ]:
# can our function handle arrays?

rnp = np.array(r)
circle_area7(rnp)

# what type of variable did the function return?

### It is very useful to add some documentation string info to your functions

In [ ]:
def circle_area7(radius = 3):
    """ Returns the area of a circle given the radius. 
    Assumes the radius is 3 if not supplied. """
    import numpy as np
    
    return np.pi*radius**2

Now my note in the triple quotes shows up as a docstring

In [ ]:
circle_area7?

There is a standard practice in programming to write out the Parameters (inputs/arguments) and Returns (output) in the docstring. Let's look a this for a predefined function and then make if for our simple function.

In [ ]:
import numpy as np

In [ ]:
np.max?

In [ ]:
def circle_area7(radius = 3):
    """ Returns the area of a circle given the radius. 
    
    Parameters
    ----------
    radus: array like, radius of the circle
    Assumes the radius is 3 if not supplied.
    
    Returns
    -------
    area: ndarray or scalar
    Returns the area for the given radii
    
    """
    
    import numpy as np
    
    return np.pi*radius**2

In [ ]:
circle_area7?

# Lab 7.1

**E.1** Complete Introduction to Data Visualization with Matplotlib Chapters 1-2


**E.2** Make notes for yourself on progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
#you can make a matrix within a plot to better help plot out data
#after initializing a subplot with fig, ax = plt.subplot(), you can include matrix parameters within the ()
#in order to utilize these then you would need to populate them with ax[#,#].plot(data data data)

#REMINDER if asking for an index it is literally just variabe/dictionary/data_set name.index, ex. pop.index


#annotate in python : ax.annotate('text that you wish to input', xy = (location of annotated object (ex. 0,0)), xytext = (location of text placement (ex. 1,1)), arrowprops = {'color':
#'desired color', 'arrowstyle':'desired arrow style (ex. '->')'})

### This week's project:

For Monday's class you will write two functions that work on your dataset (you can use the same dataset or a different one). The first function will do some sort of analysis, manipulation or calculation, the second will be a plotting function. The idea here is that if you had another datafile that was similar, you could use the function to do the operation again easily.

**E.3** Write one or more functions that manipulate your dataset and do some sort of analysis. You will present these to the class on Monday.

**E.4** If you haven't yet, complete the introductions assignment on slack (add the channel, introduce yourself)